package com.thomsonreuters.wokmws.cxf.woksearchlite;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 2.6.1 2012-08-13T08:31:40.747-04:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "AuthenticationException", targetNamespace = "http://woksearchlite.cxf.wokmws.thomsonreuters.com")
public class AuthenticationException_Exception extends Exception {

	private static final long serialVersionUID = 1L;
	private com.thomsonreuters.wokmws.cxf.woksearchlite.AuthenticationException authenticationException;

	public AuthenticationException_Exception() {
		super();
	}

	public AuthenticationException_Exception(String message) {
		super(message);
	}

	public AuthenticationException_Exception(String message, Throwable cause) {
		super(message, cause);
	}

	public AuthenticationException_Exception(
			String message,
			com.thomsonreuters.wokmws.cxf.woksearchlite.AuthenticationException authenticationException) {
		super(message);
		this.authenticationException = authenticationException;
	}

	public AuthenticationException_Exception(
			String message,
			com.thomsonreuters.wokmws.cxf.woksearchlite.AuthenticationException authenticationException,
			Throwable cause) {
		super(message, cause);
		this.authenticationException = authenticationException;
	}

	public com.thomsonreuters.wokmws.cxf.woksearchlite.AuthenticationException getFaultInfo() {
		return this.authenticationException;
	}
}
