
package com.thomsonreuters.wokmws.cxf.woksearchlite;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-08-13T08:31:40.714-04:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "ESTIWSException", targetNamespace = "http://woksearchlite.cxf.wokmws.thomsonreuters.com")
public class ESTIWSException_Exception extends Exception {
	private static final long serialVersionUID = 1L;

    private com.thomsonreuters.wokmws.cxf.woksearchlite.ESTIWSException estiwsException;

    public ESTIWSException_Exception() {
        super();
    }
    
    public ESTIWSException_Exception(String message) {
        super(message);
    }
    
    public ESTIWSException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ESTIWSException_Exception(String message, com.thomsonreuters.wokmws.cxf.woksearchlite.ESTIWSException estiwsException) {
        super(message);
        this.estiwsException = estiwsException;
    }

    public ESTIWSException_Exception(String message, com.thomsonreuters.wokmws.cxf.woksearchlite.ESTIWSException estiwsException, Throwable cause) {
        super(message, cause);
        this.estiwsException = estiwsException;
    }

    public com.thomsonreuters.wokmws.cxf.woksearchlite.ESTIWSException getFaultInfo() {
        return this.estiwsException;
    }
}
