package com.thomsonreuters.wokmws.cxf.woksearchlite;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 2.6.1 2012-08-13T08:31:40.731-04:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "InternalServerException", targetNamespace = "http://woksearchlite.cxf.wokmws.thomsonreuters.com")
public class InternalServerException_Exception extends Exception {
	private static final long serialVersionUID = 1L;

	private com.thomsonreuters.wokmws.cxf.woksearchlite.InternalServerException internalServerException;

	public InternalServerException_Exception() {
		super();
	}

	public InternalServerException_Exception(String message) {
		super(message);
	}

	public InternalServerException_Exception(String message, Throwable cause) {
		super(message, cause);
	}

	public InternalServerException_Exception(
			String message,
			com.thomsonreuters.wokmws.cxf.woksearchlite.InternalServerException internalServerException) {
		super(message);
		this.internalServerException = internalServerException;
	}

	public InternalServerException_Exception(
			String message,
			com.thomsonreuters.wokmws.cxf.woksearchlite.InternalServerException internalServerException,
			Throwable cause) {
		super(message, cause);
		this.internalServerException = internalServerException;
	}

	public com.thomsonreuters.wokmws.cxf.woksearchlite.InternalServerException getFaultInfo() {
		return this.internalServerException;
	}
}
