package com.thomsonreuters.wokmws.cxf.woksearchlite;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-08-13T08:31:40.873-04:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://woksearchlite.cxf.wokmws.thomsonreuters.com", name = "WokSearchLite")
@XmlSeeAlso({ObjectFactory.class})
public interface WokSearchLite {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "retrieveById", targetNamespace = "http://woksearchlite.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveById")
    @WebMethod
    @ResponseWrapper(localName = "retrieveByIdResponse", targetNamespace = "http://woksearchlite.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveByIdResponse")
    public com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults retrieveById(
        @WebParam(name = "databaseId", targetNamespace = "")
        java.lang.String databaseId,
        @WebParam(name = "uids", targetNamespace = "")
        java.util.List<java.lang.String> uids,
        @WebParam(name = "queryLanguage", targetNamespace = "")
        java.lang.String queryLanguage,
        @WebParam(name = "retrieveParameters", targetNamespace = "")
        com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveParameters retrieveParameters
    ) throws ESTIWSException_Exception, InternalServerException_Exception, AuthenticationException_Exception, QueryException_Exception, InvalidInputException_Exception, SessionException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "citingArticles", targetNamespace = "http://woksearchlite.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearchlite.CitingArticles")
    @WebMethod
    @ResponseWrapper(localName = "citingArticlesResponse", targetNamespace = "http://woksearchlite.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearchlite.CitingArticlesResponse")
    public com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults citingArticles(
        @WebParam(name = "databaseId", targetNamespace = "")
        java.lang.String databaseId,
        @WebParam(name = "uid", targetNamespace = "")
        java.lang.String uid,
        @WebParam(name = "editionDesc", targetNamespace = "")
        java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.EditionDesc> editionDesc,
        @WebParam(name = "timeSpan", targetNamespace = "")
        com.thomsonreuters.wokmws.cxf.woksearchlite.TimeSpan timeSpan,
        @WebParam(name = "queryLanguage", targetNamespace = "")
        java.lang.String queryLanguage,
        @WebParam(name = "retrieveParameters", targetNamespace = "")
        com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveParameters retrieveParameters
    ) throws ESTIWSException_Exception, InternalServerException_Exception, AuthenticationException_Exception, QueryException_Exception, InvalidInputException_Exception, SessionException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "retrieve", targetNamespace = "http://woksearchlite.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearchlite.Retrieve")
    @WebMethod
    @ResponseWrapper(localName = "retrieveResponse", targetNamespace = "http://woksearchlite.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveResponse")
    public com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults retrieve(
        @WebParam(name = "queryId", targetNamespace = "")
        java.lang.String queryId,
        @WebParam(name = "retrieveParameters", targetNamespace = "")
        com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveParameters retrieveParameters
    ) throws ESTIWSException_Exception, InternalServerException_Exception, AuthenticationException_Exception, QueryException_Exception, InvalidInputException_Exception, SessionException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "relatedRecords", targetNamespace = "http://woksearchlite.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearchlite.RelatedRecords")
    @WebMethod
    @ResponseWrapper(localName = "relatedRecordsResponse", targetNamespace = "http://woksearchlite.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearchlite.RelatedRecordsResponse")
    public com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults relatedRecords(
        @WebParam(name = "databaseId", targetNamespace = "")
        java.lang.String databaseId,
        @WebParam(name = "uid", targetNamespace = "")
        java.lang.String uid,
        @WebParam(name = "editionDesc", targetNamespace = "")
        java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.EditionDesc> editionDesc,
        @WebParam(name = "timeSpan", targetNamespace = "")
        com.thomsonreuters.wokmws.cxf.woksearchlite.TimeSpan timeSpan,
        @WebParam(name = "queryLanguage", targetNamespace = "")
        java.lang.String queryLanguage,
        @WebParam(name = "retrieveParameters", targetNamespace = "")
        com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveParameters retrieveParameters
    ) throws ESTIWSException_Exception, InternalServerException_Exception, AuthenticationException_Exception, QueryException_Exception, InvalidInputException_Exception, SessionException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "search", targetNamespace = "http://woksearchlite.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearchlite.Search")
    @WebMethod
    @ResponseWrapper(localName = "searchResponse", targetNamespace = "http://woksearchlite.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResponse")
    public com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults search(
        @WebParam(name = "queryParameters", targetNamespace = "")
        com.thomsonreuters.wokmws.cxf.woksearchlite.QueryParameters queryParameters,
        @WebParam(name = "retrieveParameters", targetNamespace = "")
        com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveParameters retrieveParameters
    ) throws ESTIWSException_Exception, InternalServerException_Exception, AuthenticationException_Exception, QueryException_Exception, InvalidInputException_Exception, SessionException_Exception;
}
