
package com.thomsonreuters.wokmws.cxf.woksearchlite;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-08-13T08:31:40.604-04:00
 * Generated source version: 2.6.1
 * 
 */
public final class WokSearchLite_WokSearchLitePort_Client {

    private static final QName SERVICE_NAME = new QName("http://woksearchlite.cxf.wokmws.thomsonreuters.com", "WokSearchLiteService");

    private WokSearchLite_WokSearchLitePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WokSearchLiteService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WokSearchLiteService ss = new WokSearchLiteService(wsdlURL, SERVICE_NAME);
        WokSearchLite port = ss.getWokSearchLitePort();  
        
        {
        System.out.println("Invoking retrieveById...");
        java.lang.String _retrieveById_databaseId = "_retrieveById_databaseId-592994854";
        java.util.List<java.lang.String> _retrieveById_uids = new java.util.ArrayList<java.lang.String>();
        java.lang.String _retrieveById_uidsVal1 = "_retrieveById_uidsVal1004849879";
        _retrieveById_uids.add(_retrieveById_uidsVal1);
        java.lang.String _retrieveById_queryLanguage = "_retrieveById_queryLanguage-974344804";
        com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveParameters _retrieveById_retrieveParameters = new com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveParameters();
        _retrieveById_retrieveParameters.setCount(-1732353338);
        java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.QueryField> _retrieveById_retrieveParametersFields = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.QueryField>();
        com.thomsonreuters.wokmws.cxf.woksearchlite.QueryField _retrieveById_retrieveParametersFieldsVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.QueryField();
        _retrieveById_retrieveParametersFieldsVal1.setName("Name-1953671989");
        _retrieveById_retrieveParametersFieldsVal1.setSort("Sort138056409");
        _retrieveById_retrieveParametersFields.add(_retrieveById_retrieveParametersFieldsVal1);
        _retrieveById_retrieveParameters.getFields().addAll(_retrieveById_retrieveParametersFields);
        _retrieveById_retrieveParameters.setFirstRecord(1514129477);
        try {
            com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults _retrieveById__return = port.retrieveById(_retrieveById_databaseId, _retrieveById_uids, _retrieveById_queryLanguage, _retrieveById_retrieveParameters);
            System.out.println("retrieveById.result=" + _retrieveById__return);

        } catch (ESTIWSException_Exception e) { 
            System.out.println("Expected exception: ESTIWSException has occurred.");
            System.out.println(e.toString());
        } catch (InternalServerException_Exception e) { 
            System.out.println("Expected exception: InternalServerException has occurred.");
            System.out.println(e.toString());
        } catch (AuthenticationException_Exception e) { 
            System.out.println("Expected exception: AuthenticationException has occurred.");
            System.out.println(e.toString());
        } catch (QueryException_Exception e) { 
            System.out.println("Expected exception: QueryException has occurred.");
            System.out.println(e.toString());
        } catch (InvalidInputException_Exception e) { 
            System.out.println("Expected exception: InvalidInputException has occurred.");
            System.out.println(e.toString());
        } catch (SessionException_Exception e) { 
            System.out.println("Expected exception: SessionException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking citingArticles...");
        java.lang.String _citingArticles_databaseId = "_citingArticles_databaseId-184158262";
        java.lang.String _citingArticles_uid = "_citingArticles_uid-1142570468";
        java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.EditionDesc> _citingArticles_editionDesc = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.EditionDesc>();
        com.thomsonreuters.wokmws.cxf.woksearchlite.EditionDesc _citingArticles_editionDescVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.EditionDesc();
        _citingArticles_editionDescVal1.setCollection("Collection1523374787");
        _citingArticles_editionDescVal1.setEdition("Edition-1954264570");
        _citingArticles_editionDesc.add(_citingArticles_editionDescVal1);
        com.thomsonreuters.wokmws.cxf.woksearchlite.TimeSpan _citingArticles_timeSpan = new com.thomsonreuters.wokmws.cxf.woksearchlite.TimeSpan();
        _citingArticles_timeSpan.setBegin("Begin-537066075");
        _citingArticles_timeSpan.setEnd("End1802829438");
        java.lang.String _citingArticles_queryLanguage = "_citingArticles_queryLanguage463261574";
        com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveParameters _citingArticles_retrieveParameters = new com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveParameters();
        _citingArticles_retrieveParameters.setCount(-527124704);
        java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.QueryField> _citingArticles_retrieveParametersFields = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.QueryField>();
        com.thomsonreuters.wokmws.cxf.woksearchlite.QueryField _citingArticles_retrieveParametersFieldsVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.QueryField();
        _citingArticles_retrieveParametersFieldsVal1.setName("Name2028467613");
        _citingArticles_retrieveParametersFieldsVal1.setSort("Sort1110921924");
        _citingArticles_retrieveParametersFields.add(_citingArticles_retrieveParametersFieldsVal1);
        _citingArticles_retrieveParameters.getFields().addAll(_citingArticles_retrieveParametersFields);
        _citingArticles_retrieveParameters.setFirstRecord(2062148140);
        try {
            com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults _citingArticles__return = port.citingArticles(_citingArticles_databaseId, _citingArticles_uid, _citingArticles_editionDesc, _citingArticles_timeSpan, _citingArticles_queryLanguage, _citingArticles_retrieveParameters);
            System.out.println("citingArticles.result=" + _citingArticles__return);

        } catch (ESTIWSException_Exception e) { 
            System.out.println("Expected exception: ESTIWSException has occurred.");
            System.out.println(e.toString());
        } catch (InternalServerException_Exception e) { 
            System.out.println("Expected exception: InternalServerException has occurred.");
            System.out.println(e.toString());
        } catch (AuthenticationException_Exception e) { 
            System.out.println("Expected exception: AuthenticationException has occurred.");
            System.out.println(e.toString());
        } catch (QueryException_Exception e) { 
            System.out.println("Expected exception: QueryException has occurred.");
            System.out.println(e.toString());
        } catch (InvalidInputException_Exception e) { 
            System.out.println("Expected exception: InvalidInputException has occurred.");
            System.out.println(e.toString());
        } catch (SessionException_Exception e) { 
            System.out.println("Expected exception: SessionException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking retrieve...");
        java.lang.String _retrieve_queryId = "_retrieve_queryId84977760";
        com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveParameters _retrieve_retrieveParameters = new com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveParameters();
        _retrieve_retrieveParameters.setCount(1748365873);
        java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.QueryField> _retrieve_retrieveParametersFields = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.QueryField>();
        com.thomsonreuters.wokmws.cxf.woksearchlite.QueryField _retrieve_retrieveParametersFieldsVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.QueryField();
        _retrieve_retrieveParametersFieldsVal1.setName("Name23326661");
        _retrieve_retrieveParametersFieldsVal1.setSort("Sort-457118748");
        _retrieve_retrieveParametersFields.add(_retrieve_retrieveParametersFieldsVal1);
        _retrieve_retrieveParameters.getFields().addAll(_retrieve_retrieveParametersFields);
        _retrieve_retrieveParameters.setFirstRecord(-1305927773);
        try {
            com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults _retrieve__return = port.retrieve(_retrieve_queryId, _retrieve_retrieveParameters);
            System.out.println("retrieve.result=" + _retrieve__return);

        } catch (ESTIWSException_Exception e) { 
            System.out.println("Expected exception: ESTIWSException has occurred.");
            System.out.println(e.toString());
        } catch (InternalServerException_Exception e) { 
            System.out.println("Expected exception: InternalServerException has occurred.");
            System.out.println(e.toString());
        } catch (AuthenticationException_Exception e) { 
            System.out.println("Expected exception: AuthenticationException has occurred.");
            System.out.println(e.toString());
        } catch (QueryException_Exception e) { 
            System.out.println("Expected exception: QueryException has occurred.");
            System.out.println(e.toString());
        } catch (InvalidInputException_Exception e) { 
            System.out.println("Expected exception: InvalidInputException has occurred.");
            System.out.println(e.toString());
        } catch (SessionException_Exception e) { 
            System.out.println("Expected exception: SessionException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking relatedRecords...");
        java.lang.String _relatedRecords_databaseId = "_relatedRecords_databaseId-199263415";
        java.lang.String _relatedRecords_uid = "_relatedRecords_uid2080948357";
        java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.EditionDesc> _relatedRecords_editionDesc = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.EditionDesc>();
        com.thomsonreuters.wokmws.cxf.woksearchlite.EditionDesc _relatedRecords_editionDescVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.EditionDesc();
        _relatedRecords_editionDescVal1.setCollection("Collection-883884194");
        _relatedRecords_editionDescVal1.setEdition("Edition-633397091");
        _relatedRecords_editionDesc.add(_relatedRecords_editionDescVal1);
        com.thomsonreuters.wokmws.cxf.woksearchlite.TimeSpan _relatedRecords_timeSpan = new com.thomsonreuters.wokmws.cxf.woksearchlite.TimeSpan();
        _relatedRecords_timeSpan.setBegin("Begin-585266769");
        _relatedRecords_timeSpan.setEnd("End-963724650");
        java.lang.String _relatedRecords_queryLanguage = "_relatedRecords_queryLanguage-1767146663";
        com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveParameters _relatedRecords_retrieveParameters = new com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveParameters();
        _relatedRecords_retrieveParameters.setCount(-959671851);
        java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.QueryField> _relatedRecords_retrieveParametersFields = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.QueryField>();
        com.thomsonreuters.wokmws.cxf.woksearchlite.QueryField _relatedRecords_retrieveParametersFieldsVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.QueryField();
        _relatedRecords_retrieveParametersFieldsVal1.setName("Name1005254077");
        _relatedRecords_retrieveParametersFieldsVal1.setSort("Sort-980922180");
        _relatedRecords_retrieveParametersFields.add(_relatedRecords_retrieveParametersFieldsVal1);
        _relatedRecords_retrieveParameters.getFields().addAll(_relatedRecords_retrieveParametersFields);
        _relatedRecords_retrieveParameters.setFirstRecord(-723897735);
        try {
            com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults _relatedRecords__return = port.relatedRecords(_relatedRecords_databaseId, _relatedRecords_uid, _relatedRecords_editionDesc, _relatedRecords_timeSpan, _relatedRecords_queryLanguage, _relatedRecords_retrieveParameters);
            System.out.println("relatedRecords.result=" + _relatedRecords__return);

        } catch (ESTIWSException_Exception e) { 
            System.out.println("Expected exception: ESTIWSException has occurred.");
            System.out.println(e.toString());
        } catch (InternalServerException_Exception e) { 
            System.out.println("Expected exception: InternalServerException has occurred.");
            System.out.println(e.toString());
        } catch (AuthenticationException_Exception e) { 
            System.out.println("Expected exception: AuthenticationException has occurred.");
            System.out.println(e.toString());
        } catch (QueryException_Exception e) { 
            System.out.println("Expected exception: QueryException has occurred.");
            System.out.println(e.toString());
        } catch (InvalidInputException_Exception e) { 
            System.out.println("Expected exception: InvalidInputException has occurred.");
            System.out.println(e.toString());
        } catch (SessionException_Exception e) { 
            System.out.println("Expected exception: SessionException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking search...");
        com.thomsonreuters.wokmws.cxf.woksearchlite.QueryParameters _search_queryParameters = new com.thomsonreuters.wokmws.cxf.woksearchlite.QueryParameters();
        _search_queryParameters.setDatabaseID("DatabaseID151759347");
        java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.EditionDesc> _search_queryParametersEditions = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.EditionDesc>();
        com.thomsonreuters.wokmws.cxf.woksearchlite.EditionDesc _search_queryParametersEditionsVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.EditionDesc();
        _search_queryParametersEditionsVal1.setCollection("Collection396957016");
        _search_queryParametersEditionsVal1.setEdition("Edition908192719");
        _search_queryParametersEditions.add(_search_queryParametersEditionsVal1);
        _search_queryParameters.getEditions().addAll(_search_queryParametersEditions);
        _search_queryParameters.setQueryLanguage("QueryLanguage143637597");
        _search_queryParameters.setSymbolicTimeSpan("SymbolicTimeSpan-95326915");
        com.thomsonreuters.wokmws.cxf.woksearchlite.TimeSpan _search_queryParametersTimeSpan = new com.thomsonreuters.wokmws.cxf.woksearchlite.TimeSpan();
        _search_queryParametersTimeSpan.setBegin("Begin-2032417508");
        _search_queryParametersTimeSpan.setEnd("End-1113158171");
        _search_queryParameters.setTimeSpan(_search_queryParametersTimeSpan);
        _search_queryParameters.setUserQuery("UserQuery207832048");
        com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveParameters _search_retrieveParameters = new com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveParameters();
        _search_retrieveParameters.setCount(-984350881);
        java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.QueryField> _search_retrieveParametersFields = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.QueryField>();
        com.thomsonreuters.wokmws.cxf.woksearchlite.QueryField _search_retrieveParametersFieldsVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.QueryField();
        _search_retrieveParametersFieldsVal1.setName("Name679497944");
        _search_retrieveParametersFieldsVal1.setSort("Sort-267844689");
        _search_retrieveParametersFields.add(_search_retrieveParametersFieldsVal1);
        _search_retrieveParameters.getFields().addAll(_search_retrieveParametersFields);
        _search_retrieveParameters.setFirstRecord(1573545727);
        try {
            com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults _search__return = port.search(_search_queryParameters, _search_retrieveParameters);
            System.out.println("search.result=" + _search__return);

        } catch (ESTIWSException_Exception e) { 
            System.out.println("Expected exception: ESTIWSException has occurred.");
            System.out.println(e.toString());
        } catch (InternalServerException_Exception e) { 
            System.out.println("Expected exception: InternalServerException has occurred.");
            System.out.println(e.toString());
        } catch (AuthenticationException_Exception e) { 
            System.out.println("Expected exception: AuthenticationException has occurred.");
            System.out.println(e.toString());
        } catch (QueryException_Exception e) { 
            System.out.println("Expected exception: QueryException has occurred.");
            System.out.println(e.toString());
        } catch (InvalidInputException_Exception e) { 
            System.out.println("Expected exception: InvalidInputException has occurred.");
            System.out.println(e.toString());
        } catch (SessionException_Exception e) { 
            System.out.println("Expected exception: SessionException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
