
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.thomsonreuters.wokmws.cxf.woksearchlite;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-08-13T08:31:40.832-04:00
 * Generated source version: 2.6.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "WokSearchLiteService",
                      portName = "WokSearchLitePort",
                      targetNamespace = "http://woksearchlite.cxf.wokmws.thomsonreuters.com",
                      wsdlLocation = "http://search.isiknowledge.com/esti/wokmws/ws/WokSearchLite?wsdl",
                      endpointInterface = "com.thomsonreuters.wokmws.cxf.woksearchlite.WokSearchLite")
                      
public class WokSearchLiteImpl implements WokSearchLite {

    private static final Logger LOG = Logger.getLogger(WokSearchLiteImpl.class.getName());

    /* (non-Javadoc)
     * @see com.thomsonreuters.wokmws.cxf.woksearchlite.WokSearchLite#retrieveById(java.lang.String  databaseId ,)java.util.List<java.lang.String>  uids ,)java.lang.String  queryLanguage ,)com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveParameters  retrieveParameters )*
     */
    public com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults retrieveById(java.lang.String databaseId,java.util.List<java.lang.String> uids,java.lang.String queryLanguage,com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveParameters retrieveParameters) throws ESTIWSException_Exception , InternalServerException_Exception , AuthenticationException_Exception , QueryException_Exception , InvalidInputException_Exception , SessionException_Exception    { 
        LOG.info("Executing operation retrieveById");
        System.out.println(databaseId);
        System.out.println(uids);
        System.out.println(queryLanguage);
        System.out.println(retrieveParameters);
        try {
            com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults _return = new com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LiteRecord _returnParent = new com.thomsonreuters.wokmws.cxf.woksearchlite.LiteRecord();
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnParentAuthors = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair _returnParentAuthorsVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair();
            _returnParentAuthorsVal1.setLabel("Label1172163946");
            java.util.List<java.lang.String> _returnParentAuthorsVal1Values = new java.util.ArrayList<java.lang.String>();
            _returnParentAuthorsVal1.getValues().addAll(_returnParentAuthorsVal1Values);
            _returnParentAuthors.add(_returnParentAuthorsVal1);
            _returnParent.getAuthors().addAll(_returnParentAuthors);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnParentKeywords = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair _returnParentKeywordsVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair();
            _returnParentKeywordsVal1.setLabel("Label-1899630788");
            java.util.List<java.lang.String> _returnParentKeywordsVal1Values = new java.util.ArrayList<java.lang.String>();
            _returnParentKeywordsVal1.getValues().addAll(_returnParentKeywordsVal1Values);
            _returnParentKeywords.add(_returnParentKeywordsVal1);
            _returnParent.getKeywords().addAll(_returnParentKeywords);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnParentOther = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair _returnParentOtherVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair();
            _returnParentOtherVal1.setLabel("Label-1585166301");
            java.util.List<java.lang.String> _returnParentOtherVal1Values = new java.util.ArrayList<java.lang.String>();
            _returnParentOtherVal1.getValues().addAll(_returnParentOtherVal1Values);
            _returnParentOther.add(_returnParentOtherVal1);
            _returnParent.getOther().addAll(_returnParentOther);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnParentSource = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair _returnParentSourceVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair();
            _returnParentSourceVal1.setLabel("Label186186508");
            java.util.List<java.lang.String> _returnParentSourceVal1Values = new java.util.ArrayList<java.lang.String>();
            _returnParentSourceVal1.getValues().addAll(_returnParentSourceVal1Values);
            _returnParentSource.add(_returnParentSourceVal1);
            _returnParent.getSource().addAll(_returnParentSource);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnParentTitle = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair _returnParentTitleVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair();
            _returnParentTitleVal1.setLabel("Label1962595358");
            java.util.List<java.lang.String> _returnParentTitleVal1Values = new java.util.ArrayList<java.lang.String>();
            _returnParentTitleVal1.getValues().addAll(_returnParentTitleVal1Values);
            _returnParentTitle.add(_returnParentTitleVal1);
            _returnParent.getTitle().addAll(_returnParentTitle);
            _returnParent.setUT("UT-1171929903");
            _return.setParent(_returnParent);
            _return.setQueryID("QueryID862715483");
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LiteRecord> _returnRecords = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LiteRecord>();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LiteRecord _returnRecordsVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.LiteRecord();
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnRecordsVal1Authors = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getAuthors().addAll(_returnRecordsVal1Authors);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnRecordsVal1Keywords = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getKeywords().addAll(_returnRecordsVal1Keywords);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnRecordsVal1Other = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getOther().addAll(_returnRecordsVal1Other);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnRecordsVal1Source = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getSource().addAll(_returnRecordsVal1Source);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnRecordsVal1Title = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getTitle().addAll(_returnRecordsVal1Title);
            _returnRecordsVal1.setUT("UT-872952991");
            _returnRecords.add(_returnRecordsVal1);
            _return.getRecords().addAll(_returnRecords);
            _return.setRecordsFound(347965036);
            _return.setRecordsSearched(2090692944619120060l);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ESTIWSException_Exception("ESTIWSException...");
        //throw new InternalServerException_Exception("InternalServerException...");
        //throw new AuthenticationException_Exception("AuthenticationException...");
        //throw new QueryException_Exception("QueryException...");
        //throw new InvalidInputException_Exception("InvalidInputException...");
        //throw new SessionException_Exception("SessionException...");
    }

    /* (non-Javadoc)
     * @see com.thomsonreuters.wokmws.cxf.woksearchlite.WokSearchLite#citingArticles(java.lang.String  databaseId ,)java.lang.String  uid ,)java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.EditionDesc>  editionDesc ,)com.thomsonreuters.wokmws.cxf.woksearchlite.TimeSpan  timeSpan ,)java.lang.String  queryLanguage ,)com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveParameters  retrieveParameters )*
     */
    public com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults citingArticles(java.lang.String databaseId,java.lang.String uid,java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.EditionDesc> editionDesc,com.thomsonreuters.wokmws.cxf.woksearchlite.TimeSpan timeSpan,java.lang.String queryLanguage,com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveParameters retrieveParameters) throws ESTIWSException_Exception , InternalServerException_Exception , AuthenticationException_Exception , QueryException_Exception , InvalidInputException_Exception , SessionException_Exception    { 
        LOG.info("Executing operation citingArticles");
        System.out.println(databaseId);
        System.out.println(uid);
        System.out.println(editionDesc);
        System.out.println(timeSpan);
        System.out.println(queryLanguage);
        System.out.println(retrieveParameters);
        try {
            com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults _return = new com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LiteRecord _returnParent = new com.thomsonreuters.wokmws.cxf.woksearchlite.LiteRecord();
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnParentAuthors = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair _returnParentAuthorsVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair();
            _returnParentAuthorsVal1.setLabel("Label-1455381401");
            java.util.List<java.lang.String> _returnParentAuthorsVal1Values = new java.util.ArrayList<java.lang.String>();
            _returnParentAuthorsVal1.getValues().addAll(_returnParentAuthorsVal1Values);
            _returnParentAuthors.add(_returnParentAuthorsVal1);
            _returnParent.getAuthors().addAll(_returnParentAuthors);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnParentKeywords = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair _returnParentKeywordsVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair();
            _returnParentKeywordsVal1.setLabel("Label613226549");
            java.util.List<java.lang.String> _returnParentKeywordsVal1Values = new java.util.ArrayList<java.lang.String>();
            _returnParentKeywordsVal1.getValues().addAll(_returnParentKeywordsVal1Values);
            _returnParentKeywords.add(_returnParentKeywordsVal1);
            _returnParent.getKeywords().addAll(_returnParentKeywords);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnParentOther = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair _returnParentOtherVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair();
            _returnParentOtherVal1.setLabel("Label1558180182");
            java.util.List<java.lang.String> _returnParentOtherVal1Values = new java.util.ArrayList<java.lang.String>();
            _returnParentOtherVal1.getValues().addAll(_returnParentOtherVal1Values);
            _returnParentOther.add(_returnParentOtherVal1);
            _returnParent.getOther().addAll(_returnParentOther);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnParentSource = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair _returnParentSourceVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair();
            _returnParentSourceVal1.setLabel("Label-618304421");
            java.util.List<java.lang.String> _returnParentSourceVal1Values = new java.util.ArrayList<java.lang.String>();
            _returnParentSourceVal1.getValues().addAll(_returnParentSourceVal1Values);
            _returnParentSource.add(_returnParentSourceVal1);
            _returnParent.getSource().addAll(_returnParentSource);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnParentTitle = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair _returnParentTitleVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair();
            _returnParentTitleVal1.setLabel("Label-918601672");
            java.util.List<java.lang.String> _returnParentTitleVal1Values = new java.util.ArrayList<java.lang.String>();
            _returnParentTitleVal1.getValues().addAll(_returnParentTitleVal1Values);
            _returnParentTitle.add(_returnParentTitleVal1);
            _returnParent.getTitle().addAll(_returnParentTitle);
            _returnParent.setUT("UT-1647890088");
            _return.setParent(_returnParent);
            _return.setQueryID("QueryID1773569695");
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LiteRecord> _returnRecords = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LiteRecord>();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LiteRecord _returnRecordsVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.LiteRecord();
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnRecordsVal1Authors = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getAuthors().addAll(_returnRecordsVal1Authors);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnRecordsVal1Keywords = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getKeywords().addAll(_returnRecordsVal1Keywords);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnRecordsVal1Other = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getOther().addAll(_returnRecordsVal1Other);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnRecordsVal1Source = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getSource().addAll(_returnRecordsVal1Source);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnRecordsVal1Title = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getTitle().addAll(_returnRecordsVal1Title);
            _returnRecordsVal1.setUT("UT-355089509");
            _returnRecords.add(_returnRecordsVal1);
            _return.getRecords().addAll(_returnRecords);
            _return.setRecordsFound(-1925453711);
            _return.setRecordsSearched(-7162046211180115856l);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ESTIWSException_Exception("ESTIWSException...");
        //throw new InternalServerException_Exception("InternalServerException...");
        //throw new AuthenticationException_Exception("AuthenticationException...");
        //throw new QueryException_Exception("QueryException...");
        //throw new InvalidInputException_Exception("InvalidInputException...");
        //throw new SessionException_Exception("SessionException...");
    }

    /* (non-Javadoc)
     * @see com.thomsonreuters.wokmws.cxf.woksearchlite.WokSearchLite#retrieve(java.lang.String  queryId ,)com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveParameters  retrieveParameters )*
     */
    public com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults retrieve(java.lang.String queryId,com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveParameters retrieveParameters) throws ESTIWSException_Exception , InternalServerException_Exception , AuthenticationException_Exception , QueryException_Exception , InvalidInputException_Exception , SessionException_Exception    { 
        LOG.info("Executing operation retrieve");
        System.out.println(queryId);
        System.out.println(retrieveParameters);
        try {
            com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults _return = new com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LiteRecord _returnParent = new com.thomsonreuters.wokmws.cxf.woksearchlite.LiteRecord();
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnParentAuthors = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair _returnParentAuthorsVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair();
            _returnParentAuthorsVal1.setLabel("Label1286806298");
            java.util.List<java.lang.String> _returnParentAuthorsVal1Values = new java.util.ArrayList<java.lang.String>();
            _returnParentAuthorsVal1.getValues().addAll(_returnParentAuthorsVal1Values);
            _returnParentAuthors.add(_returnParentAuthorsVal1);
            _returnParent.getAuthors().addAll(_returnParentAuthors);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnParentKeywords = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair _returnParentKeywordsVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair();
            _returnParentKeywordsVal1.setLabel("Label1445847373");
            java.util.List<java.lang.String> _returnParentKeywordsVal1Values = new java.util.ArrayList<java.lang.String>();
            _returnParentKeywordsVal1.getValues().addAll(_returnParentKeywordsVal1Values);
            _returnParentKeywords.add(_returnParentKeywordsVal1);
            _returnParent.getKeywords().addAll(_returnParentKeywords);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnParentOther = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair _returnParentOtherVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair();
            _returnParentOtherVal1.setLabel("Label2057717959");
            java.util.List<java.lang.String> _returnParentOtherVal1Values = new java.util.ArrayList<java.lang.String>();
            _returnParentOtherVal1.getValues().addAll(_returnParentOtherVal1Values);
            _returnParentOther.add(_returnParentOtherVal1);
            _returnParent.getOther().addAll(_returnParentOther);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnParentSource = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair _returnParentSourceVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair();
            _returnParentSourceVal1.setLabel("Label1643176594");
            java.util.List<java.lang.String> _returnParentSourceVal1Values = new java.util.ArrayList<java.lang.String>();
            _returnParentSourceVal1.getValues().addAll(_returnParentSourceVal1Values);
            _returnParentSource.add(_returnParentSourceVal1);
            _returnParent.getSource().addAll(_returnParentSource);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnParentTitle = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair _returnParentTitleVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair();
            _returnParentTitleVal1.setLabel("Label-792697395");
            java.util.List<java.lang.String> _returnParentTitleVal1Values = new java.util.ArrayList<java.lang.String>();
            _returnParentTitleVal1.getValues().addAll(_returnParentTitleVal1Values);
            _returnParentTitle.add(_returnParentTitleVal1);
            _returnParent.getTitle().addAll(_returnParentTitle);
            _returnParent.setUT("UT2109796847");
            _return.setParent(_returnParent);
            _return.setQueryID("QueryID1413015881");
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LiteRecord> _returnRecords = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LiteRecord>();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LiteRecord _returnRecordsVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.LiteRecord();
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnRecordsVal1Authors = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getAuthors().addAll(_returnRecordsVal1Authors);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnRecordsVal1Keywords = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getKeywords().addAll(_returnRecordsVal1Keywords);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnRecordsVal1Other = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getOther().addAll(_returnRecordsVal1Other);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnRecordsVal1Source = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getSource().addAll(_returnRecordsVal1Source);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnRecordsVal1Title = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getTitle().addAll(_returnRecordsVal1Title);
            _returnRecordsVal1.setUT("UT684521629");
            _returnRecords.add(_returnRecordsVal1);
            _return.getRecords().addAll(_returnRecords);
            _return.setRecordsFound(-1738322583);
            _return.setRecordsSearched(7474460244993398103l);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ESTIWSException_Exception("ESTIWSException...");
        //throw new InternalServerException_Exception("InternalServerException...");
        //throw new AuthenticationException_Exception("AuthenticationException...");
        //throw new QueryException_Exception("QueryException...");
        //throw new InvalidInputException_Exception("InvalidInputException...");
        //throw new SessionException_Exception("SessionException...");
    }

    /* (non-Javadoc)
     * @see com.thomsonreuters.wokmws.cxf.woksearchlite.WokSearchLite#relatedRecords(java.lang.String  databaseId ,)java.lang.String  uid ,)java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.EditionDesc>  editionDesc ,)com.thomsonreuters.wokmws.cxf.woksearchlite.TimeSpan  timeSpan ,)java.lang.String  queryLanguage ,)com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveParameters  retrieveParameters )*
     */
    public com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults relatedRecords(java.lang.String databaseId,java.lang.String uid,java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.EditionDesc> editionDesc,com.thomsonreuters.wokmws.cxf.woksearchlite.TimeSpan timeSpan,java.lang.String queryLanguage,com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveParameters retrieveParameters) throws ESTIWSException_Exception , InternalServerException_Exception , AuthenticationException_Exception , QueryException_Exception , InvalidInputException_Exception , SessionException_Exception    { 
        LOG.info("Executing operation relatedRecords");
        System.out.println(databaseId);
        System.out.println(uid);
        System.out.println(editionDesc);
        System.out.println(timeSpan);
        System.out.println(queryLanguage);
        System.out.println(retrieveParameters);
        try {
            com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults _return = new com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LiteRecord _returnParent = new com.thomsonreuters.wokmws.cxf.woksearchlite.LiteRecord();
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnParentAuthors = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair _returnParentAuthorsVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair();
            _returnParentAuthorsVal1.setLabel("Label-1141863510");
            java.util.List<java.lang.String> _returnParentAuthorsVal1Values = new java.util.ArrayList<java.lang.String>();
            _returnParentAuthorsVal1.getValues().addAll(_returnParentAuthorsVal1Values);
            _returnParentAuthors.add(_returnParentAuthorsVal1);
            _returnParent.getAuthors().addAll(_returnParentAuthors);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnParentKeywords = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair _returnParentKeywordsVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair();
            _returnParentKeywordsVal1.setLabel("Label1725118468");
            java.util.List<java.lang.String> _returnParentKeywordsVal1Values = new java.util.ArrayList<java.lang.String>();
            _returnParentKeywordsVal1.getValues().addAll(_returnParentKeywordsVal1Values);
            _returnParentKeywords.add(_returnParentKeywordsVal1);
            _returnParent.getKeywords().addAll(_returnParentKeywords);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnParentOther = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair _returnParentOtherVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair();
            _returnParentOtherVal1.setLabel("Label-343874442");
            java.util.List<java.lang.String> _returnParentOtherVal1Values = new java.util.ArrayList<java.lang.String>();
            _returnParentOtherVal1.getValues().addAll(_returnParentOtherVal1Values);
            _returnParentOther.add(_returnParentOtherVal1);
            _returnParent.getOther().addAll(_returnParentOther);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnParentSource = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair _returnParentSourceVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair();
            _returnParentSourceVal1.setLabel("Label-648819039");
            java.util.List<java.lang.String> _returnParentSourceVal1Values = new java.util.ArrayList<java.lang.String>();
            _returnParentSourceVal1.getValues().addAll(_returnParentSourceVal1Values);
            _returnParentSource.add(_returnParentSourceVal1);
            _returnParent.getSource().addAll(_returnParentSource);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnParentTitle = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair _returnParentTitleVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair();
            _returnParentTitleVal1.setLabel("Label-1616476340");
            java.util.List<java.lang.String> _returnParentTitleVal1Values = new java.util.ArrayList<java.lang.String>();
            _returnParentTitleVal1.getValues().addAll(_returnParentTitleVal1Values);
            _returnParentTitle.add(_returnParentTitleVal1);
            _returnParent.getTitle().addAll(_returnParentTitle);
            _returnParent.setUT("UT1606452220");
            _return.setParent(_returnParent);
            _return.setQueryID("QueryID-1353869379");
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LiteRecord> _returnRecords = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LiteRecord>();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LiteRecord _returnRecordsVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.LiteRecord();
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnRecordsVal1Authors = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getAuthors().addAll(_returnRecordsVal1Authors);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnRecordsVal1Keywords = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getKeywords().addAll(_returnRecordsVal1Keywords);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnRecordsVal1Other = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getOther().addAll(_returnRecordsVal1Other);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnRecordsVal1Source = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getSource().addAll(_returnRecordsVal1Source);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnRecordsVal1Title = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getTitle().addAll(_returnRecordsVal1Title);
            _returnRecordsVal1.setUT("UT780872233");
            _returnRecords.add(_returnRecordsVal1);
            _return.getRecords().addAll(_returnRecords);
            _return.setRecordsFound(-1143625281);
            _return.setRecordsSearched(493458717026984692l);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ESTIWSException_Exception("ESTIWSException...");
        //throw new InternalServerException_Exception("InternalServerException...");
        //throw new AuthenticationException_Exception("AuthenticationException...");
        //throw new QueryException_Exception("QueryException...");
        //throw new InvalidInputException_Exception("InvalidInputException...");
        //throw new SessionException_Exception("SessionException...");
    }

    /* (non-Javadoc)
     * @see com.thomsonreuters.wokmws.cxf.woksearchlite.WokSearchLite#search(com.thomsonreuters.wokmws.cxf.woksearchlite.QueryParameters  queryParameters ,)com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveParameters  retrieveParameters )*
     */
    public com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults search(com.thomsonreuters.wokmws.cxf.woksearchlite.QueryParameters queryParameters,com.thomsonreuters.wokmws.cxf.woksearchlite.RetrieveParameters retrieveParameters) throws ESTIWSException_Exception , InternalServerException_Exception , AuthenticationException_Exception , QueryException_Exception , InvalidInputException_Exception , SessionException_Exception    { 
        LOG.info("Executing operation search");
        System.out.println(queryParameters);
        System.out.println(retrieveParameters);
        try {
            com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults _return = new com.thomsonreuters.wokmws.cxf.woksearchlite.SearchResults();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LiteRecord _returnParent = new com.thomsonreuters.wokmws.cxf.woksearchlite.LiteRecord();
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnParentAuthors = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair _returnParentAuthorsVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair();
            _returnParentAuthorsVal1.setLabel("Label-338309884");
            java.util.List<java.lang.String> _returnParentAuthorsVal1Values = new java.util.ArrayList<java.lang.String>();
            _returnParentAuthorsVal1.getValues().addAll(_returnParentAuthorsVal1Values);
            _returnParentAuthors.add(_returnParentAuthorsVal1);
            _returnParent.getAuthors().addAll(_returnParentAuthors);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnParentKeywords = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair _returnParentKeywordsVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair();
            _returnParentKeywordsVal1.setLabel("Label-115721374");
            java.util.List<java.lang.String> _returnParentKeywordsVal1Values = new java.util.ArrayList<java.lang.String>();
            _returnParentKeywordsVal1.getValues().addAll(_returnParentKeywordsVal1Values);
            _returnParentKeywords.add(_returnParentKeywordsVal1);
            _returnParent.getKeywords().addAll(_returnParentKeywords);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnParentOther = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair _returnParentOtherVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair();
            _returnParentOtherVal1.setLabel("Label-176302613");
            java.util.List<java.lang.String> _returnParentOtherVal1Values = new java.util.ArrayList<java.lang.String>();
            _returnParentOtherVal1.getValues().addAll(_returnParentOtherVal1Values);
            _returnParentOther.add(_returnParentOtherVal1);
            _returnParent.getOther().addAll(_returnParentOther);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnParentSource = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair _returnParentSourceVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair();
            _returnParentSourceVal1.setLabel("Label535089296");
            java.util.List<java.lang.String> _returnParentSourceVal1Values = new java.util.ArrayList<java.lang.String>();
            _returnParentSourceVal1.getValues().addAll(_returnParentSourceVal1Values);
            _returnParentSource.add(_returnParentSourceVal1);
            _returnParent.getSource().addAll(_returnParentSource);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnParentTitle = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair _returnParentTitleVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair();
            _returnParentTitleVal1.setLabel("Label609890657");
            java.util.List<java.lang.String> _returnParentTitleVal1Values = new java.util.ArrayList<java.lang.String>();
            _returnParentTitleVal1.getValues().addAll(_returnParentTitleVal1Values);
            _returnParentTitle.add(_returnParentTitleVal1);
            _returnParent.getTitle().addAll(_returnParentTitle);
            _returnParent.setUT("UT-1367389854");
            _return.setParent(_returnParent);
            _return.setQueryID("QueryID860755072");
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LiteRecord> _returnRecords = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LiteRecord>();
            com.thomsonreuters.wokmws.cxf.woksearchlite.LiteRecord _returnRecordsVal1 = new com.thomsonreuters.wokmws.cxf.woksearchlite.LiteRecord();
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnRecordsVal1Authors = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getAuthors().addAll(_returnRecordsVal1Authors);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnRecordsVal1Keywords = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getKeywords().addAll(_returnRecordsVal1Keywords);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnRecordsVal1Other = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getOther().addAll(_returnRecordsVal1Other);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnRecordsVal1Source = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getSource().addAll(_returnRecordsVal1Source);
            java.util.List<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair> _returnRecordsVal1Title = new java.util.ArrayList<com.thomsonreuters.wokmws.cxf.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getTitle().addAll(_returnRecordsVal1Title);
            _returnRecordsVal1.setUT("UT307750440");
            _returnRecords.add(_returnRecordsVal1);
            _return.getRecords().addAll(_returnRecords);
            _return.setRecordsFound(1958885322);
            _return.setRecordsSearched(7675356106564426035l);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ESTIWSException_Exception("ESTIWSException...");
        //throw new InternalServerException_Exception("InternalServerException...");
        //throw new AuthenticationException_Exception("AuthenticationException...");
        //throw new QueryException_Exception("QueryException...");
        //throw new InvalidInputException_Exception("InvalidInputException...");
        //throw new SessionException_Exception("SessionException...");
    }

}
