package org.idiginfo.docsvc.view.rdf.vocabulary;

import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from http://commontag.org/ns# 
 * @author Auto-generated by schemagen on 01 Oct 2012
 */
public class CommonTag {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://commontag.org/ns#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>A resource (URI) representing the concepts described by the content.</p> */
    public static final Property isAbout = m_model.createProperty( "http://commontag.org/ns#isAbout" );
    
    /** <p>A local, human-readable name for a Tag.</p> */
    public static final Property label = m_model.createProperty( "http://commontag.org/ns#label" );
    
    /** <p>A a resource (URI) representing the conceptual meaning of a Tag.</p> */
    public static final Property means = m_model.createProperty( "http://commontag.org/ns#means" );
    
    /** <p>Links a resource to a Common Tag.</p> */
    public static final Property tagged = m_model.createProperty( "http://commontag.org/ns#tagged" );
    
    /** <p>The date the Tag was assigned.</p> */
    public static final Property taggingDate = m_model.createProperty( "http://commontag.org/ns#taggingDate" );
    
    /** <p>A Tag asserted by the author of a content resource.</p> */
    public static final Resource AuthorTag = m_model.createResource( "http://commontag.org/ns#AuthorTag" );
    
    /** <p>A Tag asserted by an automated tool on a content resource.</p> */
    public static final Resource AutoTag = m_model.createResource( "http://commontag.org/ns#AutoTag" );
    
    /** <p>A Tag asserted by the reader (consumer) of a content resource.</p> */
    public static final Resource ReaderTag = m_model.createResource( "http://commontag.org/ns#ReaderTag" );
    
    /** <p>A Common Tag associating a URI and a keyword to annotate a resource.</p> */
    public static final Resource Tag = m_model.createResource( "http://commontag.org/ns#Tag" );
    
    /** <p>Content which has one or more Common Tag.</p> */
    public static final Resource TaggedContent = m_model.createResource( "http://commontag.org/ns#TaggedContent" );
    
}
