package org.idiginfo.docsvc.view.rdf.vocabulary;
 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from http://purl.org/vocab/resourcelist 
 * @author Auto-generated by schemagen on 19 Sep 2012  
 */
public class ResourceList {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/vocab/resourcelist/schema#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>The alternative property is used to relate one item to another as an alternative.</p> */
    public static final Property alternative = m_model.createProperty( "http://purl.org/vocab/resourcelist/schema#alternative" );
    
    /** <p>A List may contain many Sections and Items organised in a hierarchical structure. 
     *  the contains property provides a relationshiop between the parent List and 
     *  all Sections and Items within it, whether they are attached directly or deeper 
     *  within the structure. This allows a List and all of its parts to be retrieved 
     *  with a single DESCRIBE. This is an optimisation that precludes the need for 
     *  recursive querying.</p>
     */
    public static final Property contains = m_model.createProperty( "http://purl.org/vocab/resourcelist/schema#contains" );
    
    /** <p>This property is used to capture the date a list, item, or section was created</p> */
    public static final Property created = m_model.createProperty( "http://purl.org/vocab/resourcelist/schema#created" );
    
    /** <p>This property is used to provide a description of a Resource List.</p> */
    public static final Property description = m_model.createProperty( "http://purl.org/vocab/resourcelist/schema#description" );
    
    /** <p>This property is used to capture the date a list, item, or section last updated</p> */
    public static final Property lastUpdated = m_model.createProperty( "http://purl.org/vocab/resourcelist/schema#lastUpdated" );
    
    /** <p>Sections and Items are contained within Lists, the list property allows an 
     *  easy way to get from Items and Sections that may be several levels deep to 
     *  their parent List.</p>
     */
    public static final Property list = m_model.createProperty( "http://purl.org/vocab/resourcelist/schema#list" );
    
    /** <p>DEPRECATED: The Sections and Items within a List or a Section are ordered. 
     *  The mechanism for that is a doubly linked list, using next and previous.</p>
     */
    public static final Property next = m_model.createProperty( "http://purl.org/vocab/resourcelist/schema#next" );
    
    /** <p>DEPRECATED: The Sections and Items within a List or a Section are ordered. 
     *  The mechanism for that is a doubly linked list, using next and previous.</p>
     */
    public static final Property previous = m_model.createProperty( "http://purl.org/vocab/resourcelist/schema#previous" );
    
    /** <p>The resource property relates an Item as it occurs in a List or Section to 
     *  the resource it refers to. In our current view of Resource Lists the Items 
     *  refer to resources all of which can be described using Bibliontology.</p>
     */
    public static final Property resource = m_model.createProperty( "http://purl.org/vocab/resourcelist/schema#resource" );
    
    /** <p>The usedBy property relates a List to the those rdf:resources that refer to 
     *  it.</p>
     */
    public static final Property usedBy = m_model.createProperty( "http://purl.org/vocab/resourcelist/schema#usedBy" );
    
    /** <p>The usesList property is used to relate any rdf:resource to a Resource List 
     *  it makes use of.</p>
     */
    public static final Property usesList = m_model.createProperty( "http://purl.org/vocab/resourcelist/schema#usesList" );
    
    /** <p>An Item represents a resource in the context of the list in which it is contained. 
     *  This differs from the resource itself in that a resource may be referenced 
     *  in many lists or many times within a single list. Item provides the means 
     *  to contextualize the specific reference to a resource on each list.</p>
     */
    public static final Resource Item = m_model.createResource( "http://purl.org/vocab/resourcelist/schema#Item" );
    
    /** <p>A Resource List represents an ordered collection of Items each which refers 
     *  to a resource (currently bibo:Documents) for such purposes as managing a bibliography, 
     *  circulating a reading list or similar.</p>
     */
    public static final Resource List = m_model.createResource( "http://purl.org/vocab/resourcelist/schema#List" );
    
    /** <p>A Section denotes a grouping of resources within a Resource List that are 
     *  considered related in some way.</p>
     */
    public static final Resource Section = m_model.createResource( "http://purl.org/vocab/resourcelist/schema#Section" );
    
    /** <p>This State is used to indicate that something is Draft.</p> */
    public static final Resource status_draft = m_model.createResource( "http://purl.org/vocab/resourcelist/schema#status-draft" );
    
    /** <p>This State is used to indicate that something is Published.</p> */
    public static final Resource status_published = m_model.createResource( "http://purl.org/vocab/resourcelist/schema#status-published" );
    
}
