
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.thomsonreuters.wokmws.cxf.auth;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-08-13T08:29:43.750-04:00
 * Generated source version: 2.6.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "WOKMWSAuthenticateService",
                      portName = "WOKMWSAuthenticatePort",
                      targetNamespace = "http://auth.cxf.wokmws.thomsonreuters.com",
                      wsdlLocation = "http://search.isiknowledge.com/esti/wokmws/ws/WOKMWSAuthenticate?wsdl",
                      endpointInterface = "com.thomsonreuters.wokmws.cxf.auth.WOKMWSAuthenticate")
                      
public class WOKMWSAuthenticateImpl implements WOKMWSAuthenticate {

    private static final Logger LOG = Logger.getLogger(WOKMWSAuthenticateImpl.class.getName());

    /* (non-Javadoc)
     * @see com.thomsonreuters.wokmws.cxf.auth.WOKMWSAuthenticate#closeSession(*
     */
    public void closeSession() throws SessionException_Exception , QueryException_Exception , AuthenticationException_Exception , ESTIWSException_Exception , InternalServerException_Exception , InvalidInputException_Exception    { 
        LOG.info("Executing operation closeSession");
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SessionException_Exception("SessionException...");
        //throw new QueryException_Exception("QueryException...");
        //throw new AuthenticationException_Exception("AuthenticationException...");
        //throw new ESTIWSException_Exception("ESTIWSException...");
        //throw new InternalServerException_Exception("InternalServerException...");
        //throw new InvalidInputException_Exception("InvalidInputException...");
    }

    /* (non-Javadoc)
     * @see com.thomsonreuters.wokmws.cxf.auth.WOKMWSAuthenticate#authenticate(*
     */
    public java.lang.String authenticate() throws SessionException_Exception , QueryException_Exception , AuthenticationException_Exception , ESTIWSException_Exception , InternalServerException_Exception , InvalidInputException_Exception    { 
        LOG.info("Executing operation authenticate");
        try {
            java.lang.String _return = "_return-2011388087";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SessionException_Exception("SessionException...");
        //throw new QueryException_Exception("QueryException...");
        //throw new AuthenticationException_Exception("AuthenticationException...");
        //throw new ESTIWSException_Exception("ESTIWSException...");
        //throw new InternalServerException_Exception("InternalServerException...");
        //throw new InvalidInputException_Exception("InvalidInputException...");
    }

}
