
package com.thomsonreuters.wokmws.v3.woksearchlite;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-10-29T11:33:03.500-04:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "InvalidInputException", targetNamespace = "http://woksearchlite.v3.wokmws.thomsonreuters.com")
public class InvalidInputException_Exception extends Exception {
    
    private com.thomsonreuters.wokmws.v3.woksearchlite.InvalidInputException invalidInputException;

    public InvalidInputException_Exception() {
        super();
    }
    
    public InvalidInputException_Exception(String message) {
        super(message);
    }
    
    public InvalidInputException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidInputException_Exception(String message, com.thomsonreuters.wokmws.v3.woksearchlite.InvalidInputException invalidInputException) {
        super(message);
        this.invalidInputException = invalidInputException;
    }

    public InvalidInputException_Exception(String message, com.thomsonreuters.wokmws.v3.woksearchlite.InvalidInputException invalidInputException, Throwable cause) {
        super(message, cause);
        this.invalidInputException = invalidInputException;
    }

    public com.thomsonreuters.wokmws.v3.woksearchlite.InvalidInputException getFaultInfo() {
        return this.invalidInputException;
    }
}
