
package com.thomsonreuters.wokmws.v3.woksearchlite;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-10-29T11:33:03.440-04:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "SessionException", targetNamespace = "http://woksearchlite.v3.wokmws.thomsonreuters.com")
public class SessionException_Exception extends Exception {
    
    private com.thomsonreuters.wokmws.v3.woksearchlite.SessionException sessionException;

    public SessionException_Exception() {
        super();
    }
    
    public SessionException_Exception(String message) {
        super(message);
    }
    
    public SessionException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public SessionException_Exception(String message, com.thomsonreuters.wokmws.v3.woksearchlite.SessionException sessionException) {
        super(message);
        this.sessionException = sessionException;
    }

    public SessionException_Exception(String message, com.thomsonreuters.wokmws.v3.woksearchlite.SessionException sessionException, Throwable cause) {
        super(message, cause);
        this.sessionException = sessionException;
    }

    public com.thomsonreuters.wokmws.v3.woksearchlite.SessionException getFaultInfo() {
        return this.sessionException;
    }
}
