
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.thomsonreuters.wokmws.v3.woksearchlite;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-10-29T11:33:03.630-04:00
 * Generated source version: 2.7.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "WokSearchLiteService",
                      portName = "WokSearchLitePort",
                      targetNamespace = "http://woksearchlite.v3.wokmws.thomsonreuters.com",
                      wsdlLocation = "http://search.webofknowledge.com/esti/wokmws/ws/WokSearchLite?wsdl",
                      endpointInterface = "com.thomsonreuters.wokmws.v3.woksearchlite.WokSearchLite")
                      
public class WokSearchLiteImpl implements WokSearchLite {

    private static final Logger LOG = Logger.getLogger(WokSearchLiteImpl.class.getName());

    /* (non-Javadoc)
     * @see com.thomsonreuters.wokmws.v3.woksearchlite.WokSearchLite#retrieveById(java.lang.String  databaseId ,)java.util.List<java.lang.String>  uid ,)java.lang.String  queryLanguage ,)com.thomsonreuters.wokmws.v3.woksearchlite.RetrieveParameters  retrieveParameters )*
     */
    public com.thomsonreuters.wokmws.v3.woksearchlite.SearchResults retrieveById(java.lang.String databaseId,java.util.List<java.lang.String> uid,java.lang.String queryLanguage,com.thomsonreuters.wokmws.v3.woksearchlite.RetrieveParameters retrieveParameters) throws QueryException_Exception , InternalServerException_Exception , AuthenticationException_Exception , SessionException_Exception , InvalidInputException_Exception , ESTIWSException_Exception    { 
        LOG.info("Executing operation retrieveById");
        System.out.println(databaseId);
        System.out.println(uid);
        System.out.println(queryLanguage);
        System.out.println(retrieveParameters);
        try {
            com.thomsonreuters.wokmws.v3.woksearchlite.SearchResults _return = new com.thomsonreuters.wokmws.v3.woksearchlite.SearchResults();
            _return.setQueryId("QueryId-1340397484");
            _return.setRecordsFound(-605479718);
            _return.setRecordsSearched(-7208271864419208059l);
            com.thomsonreuters.wokmws.v3.woksearchlite.LiteRecord _returnParent = new com.thomsonreuters.wokmws.v3.woksearchlite.LiteRecord();
            _returnParent.setUid("Uid-583407003");
            java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair> _returnParentTitle = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair _returnParentTitleVal1 = new com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair();
            _returnParentTitleVal1.setLabel("Label-925259003");
            java.util.List<java.lang.String> _returnParentTitleVal1Value = new java.util.ArrayList<java.lang.String>();
            _returnParentTitleVal1.getValue().addAll(_returnParentTitleVal1Value);
            _returnParentTitle.add(_returnParentTitleVal1);
            _returnParent.getTitle().addAll(_returnParentTitle);
            java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair> _returnParentSource = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair _returnParentSourceVal1 = new com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair();
            _returnParentSourceVal1.setLabel("Label-395277548");
            java.util.List<java.lang.String> _returnParentSourceVal1Value = new java.util.ArrayList<java.lang.String>();
            _returnParentSourceVal1.getValue().addAll(_returnParentSourceVal1Value);
            _returnParentSource.add(_returnParentSourceVal1);
            _returnParent.getSource().addAll(_returnParentSource);
            java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair> _returnParentAuthors = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair _returnParentAuthorsVal1 = new com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair();
            _returnParentAuthorsVal1.setLabel("Label64685965");
            java.util.List<java.lang.String> _returnParentAuthorsVal1Value = new java.util.ArrayList<java.lang.String>();
            _returnParentAuthorsVal1.getValue().addAll(_returnParentAuthorsVal1Value);
            _returnParentAuthors.add(_returnParentAuthorsVal1);
            _returnParent.getAuthors().addAll(_returnParentAuthors);
            java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair> _returnParentKeywords = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair _returnParentKeywordsVal1 = new com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair();
            _returnParentKeywordsVal1.setLabel("Label508039859");
            java.util.List<java.lang.String> _returnParentKeywordsVal1Value = new java.util.ArrayList<java.lang.String>();
            _returnParentKeywordsVal1.getValue().addAll(_returnParentKeywordsVal1Value);
            _returnParentKeywords.add(_returnParentKeywordsVal1);
            _returnParent.getKeywords().addAll(_returnParentKeywords);
            java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair> _returnParentOther = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair _returnParentOtherVal1 = new com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair();
            _returnParentOtherVal1.setLabel("Label1468930328");
            java.util.List<java.lang.String> _returnParentOtherVal1Value = new java.util.ArrayList<java.lang.String>();
            _returnParentOtherVal1.getValue().addAll(_returnParentOtherVal1Value);
            _returnParentOther.add(_returnParentOtherVal1);
            _returnParent.getOther().addAll(_returnParentOther);
            _return.setParent(_returnParent);
            java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.LiteRecord> _returnRecords = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.LiteRecord>();
            com.thomsonreuters.wokmws.v3.woksearchlite.LiteRecord _returnRecordsVal1 = new com.thomsonreuters.wokmws.v3.woksearchlite.LiteRecord();
            _returnRecordsVal1.setUid("Uid1503760289");
            java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair> _returnRecordsVal1Title = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getTitle().addAll(_returnRecordsVal1Title);
            java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair> _returnRecordsVal1Source = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getSource().addAll(_returnRecordsVal1Source);
            java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair> _returnRecordsVal1Authors = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getAuthors().addAll(_returnRecordsVal1Authors);
            java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair> _returnRecordsVal1Keywords = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getKeywords().addAll(_returnRecordsVal1Keywords);
            java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair> _returnRecordsVal1Other = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getOther().addAll(_returnRecordsVal1Other);
            _returnRecords.add(_returnRecordsVal1);
            _return.getRecords().addAll(_returnRecords);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new QueryException_Exception("QueryException...");
        //throw new InternalServerException_Exception("InternalServerException...");
        //throw new AuthenticationException_Exception("AuthenticationException...");
        //throw new SessionException_Exception("SessionException...");
        //throw new InvalidInputException_Exception("InvalidInputException...");
        //throw new ESTIWSException_Exception("ESTIWSException...");
    }

    /* (non-Javadoc)
     * @see com.thomsonreuters.wokmws.v3.woksearchlite.WokSearchLite#retrieve(java.lang.String  queryId ,)com.thomsonreuters.wokmws.v3.woksearchlite.RetrieveParameters  retrieveParameters )*
     */
    public com.thomsonreuters.wokmws.v3.woksearchlite.SearchResults retrieve(java.lang.String queryId,com.thomsonreuters.wokmws.v3.woksearchlite.RetrieveParameters retrieveParameters) throws QueryException_Exception , InternalServerException_Exception , AuthenticationException_Exception , SessionException_Exception , InvalidInputException_Exception , ESTIWSException_Exception    { 
        LOG.info("Executing operation retrieve");
        System.out.println(queryId);
        System.out.println(retrieveParameters);
        try {
            com.thomsonreuters.wokmws.v3.woksearchlite.SearchResults _return = new com.thomsonreuters.wokmws.v3.woksearchlite.SearchResults();
            _return.setQueryId("QueryId-264103891");
            _return.setRecordsFound(-1993746952);
            _return.setRecordsSearched(-9037357244429204381l);
            com.thomsonreuters.wokmws.v3.woksearchlite.LiteRecord _returnParent = new com.thomsonreuters.wokmws.v3.woksearchlite.LiteRecord();
            _returnParent.setUid("Uid1563301041");
            java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair> _returnParentTitle = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair _returnParentTitleVal1 = new com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair();
            _returnParentTitleVal1.setLabel("Label-1107712487");
            java.util.List<java.lang.String> _returnParentTitleVal1Value = new java.util.ArrayList<java.lang.String>();
            _returnParentTitleVal1.getValue().addAll(_returnParentTitleVal1Value);
            _returnParentTitle.add(_returnParentTitleVal1);
            _returnParent.getTitle().addAll(_returnParentTitle);
            java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair> _returnParentSource = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair _returnParentSourceVal1 = new com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair();
            _returnParentSourceVal1.setLabel("Label-35107468");
            java.util.List<java.lang.String> _returnParentSourceVal1Value = new java.util.ArrayList<java.lang.String>();
            _returnParentSourceVal1.getValue().addAll(_returnParentSourceVal1Value);
            _returnParentSource.add(_returnParentSourceVal1);
            _returnParent.getSource().addAll(_returnParentSource);
            java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair> _returnParentAuthors = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair _returnParentAuthorsVal1 = new com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair();
            _returnParentAuthorsVal1.setLabel("Label2044105828");
            java.util.List<java.lang.String> _returnParentAuthorsVal1Value = new java.util.ArrayList<java.lang.String>();
            _returnParentAuthorsVal1.getValue().addAll(_returnParentAuthorsVal1Value);
            _returnParentAuthors.add(_returnParentAuthorsVal1);
            _returnParent.getAuthors().addAll(_returnParentAuthors);
            java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair> _returnParentKeywords = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair _returnParentKeywordsVal1 = new com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair();
            _returnParentKeywordsVal1.setLabel("Label1188890612");
            java.util.List<java.lang.String> _returnParentKeywordsVal1Value = new java.util.ArrayList<java.lang.String>();
            _returnParentKeywordsVal1.getValue().addAll(_returnParentKeywordsVal1Value);
            _returnParentKeywords.add(_returnParentKeywordsVal1);
            _returnParent.getKeywords().addAll(_returnParentKeywords);
            java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair> _returnParentOther = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair _returnParentOtherVal1 = new com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair();
            _returnParentOtherVal1.setLabel("Label156111259");
            java.util.List<java.lang.String> _returnParentOtherVal1Value = new java.util.ArrayList<java.lang.String>();
            _returnParentOtherVal1.getValue().addAll(_returnParentOtherVal1Value);
            _returnParentOther.add(_returnParentOtherVal1);
            _returnParent.getOther().addAll(_returnParentOther);
            _return.setParent(_returnParent);
            java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.LiteRecord> _returnRecords = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.LiteRecord>();
            com.thomsonreuters.wokmws.v3.woksearchlite.LiteRecord _returnRecordsVal1 = new com.thomsonreuters.wokmws.v3.woksearchlite.LiteRecord();
            _returnRecordsVal1.setUid("Uid744557993");
            java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair> _returnRecordsVal1Title = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getTitle().addAll(_returnRecordsVal1Title);
            java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair> _returnRecordsVal1Source = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getSource().addAll(_returnRecordsVal1Source);
            java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair> _returnRecordsVal1Authors = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getAuthors().addAll(_returnRecordsVal1Authors);
            java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair> _returnRecordsVal1Keywords = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getKeywords().addAll(_returnRecordsVal1Keywords);
            java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair> _returnRecordsVal1Other = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getOther().addAll(_returnRecordsVal1Other);
            _returnRecords.add(_returnRecordsVal1);
            _return.getRecords().addAll(_returnRecords);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new QueryException_Exception("QueryException...");
        //throw new InternalServerException_Exception("InternalServerException...");
        //throw new AuthenticationException_Exception("AuthenticationException...");
        //throw new SessionException_Exception("SessionException...");
        //throw new InvalidInputException_Exception("InvalidInputException...");
        //throw new ESTIWSException_Exception("ESTIWSException...");
    }

    /* (non-Javadoc)
     * @see com.thomsonreuters.wokmws.v3.woksearchlite.WokSearchLite#search(com.thomsonreuters.wokmws.v3.woksearchlite.QueryParameters  queryParameters ,)com.thomsonreuters.wokmws.v3.woksearchlite.RetrieveParameters  retrieveParameters )*
     */
    public com.thomsonreuters.wokmws.v3.woksearchlite.SearchResults search(com.thomsonreuters.wokmws.v3.woksearchlite.QueryParameters queryParameters,com.thomsonreuters.wokmws.v3.woksearchlite.RetrieveParameters retrieveParameters) throws QueryException_Exception , InternalServerException_Exception , AuthenticationException_Exception , SessionException_Exception , InvalidInputException_Exception , ESTIWSException_Exception    { 
        LOG.info("Executing operation search");
        System.out.println(queryParameters);
        System.out.println(retrieveParameters);
        try {
            com.thomsonreuters.wokmws.v3.woksearchlite.SearchResults _return = new com.thomsonreuters.wokmws.v3.woksearchlite.SearchResults();
            _return.setQueryId("QueryId-1724456832");
            _return.setRecordsFound(1404020333);
            _return.setRecordsSearched(-1388896120800330585l);
            com.thomsonreuters.wokmws.v3.woksearchlite.LiteRecord _returnParent = new com.thomsonreuters.wokmws.v3.woksearchlite.LiteRecord();
            _returnParent.setUid("Uid1907983159");
            java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair> _returnParentTitle = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair _returnParentTitleVal1 = new com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair();
            _returnParentTitleVal1.setLabel("Label-13736081");
            java.util.List<java.lang.String> _returnParentTitleVal1Value = new java.util.ArrayList<java.lang.String>();
            _returnParentTitleVal1.getValue().addAll(_returnParentTitleVal1Value);
            _returnParentTitle.add(_returnParentTitleVal1);
            _returnParent.getTitle().addAll(_returnParentTitle);
            java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair> _returnParentSource = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair _returnParentSourceVal1 = new com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair();
            _returnParentSourceVal1.setLabel("Label1197067113");
            java.util.List<java.lang.String> _returnParentSourceVal1Value = new java.util.ArrayList<java.lang.String>();
            _returnParentSourceVal1.getValue().addAll(_returnParentSourceVal1Value);
            _returnParentSource.add(_returnParentSourceVal1);
            _returnParent.getSource().addAll(_returnParentSource);
            java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair> _returnParentAuthors = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair _returnParentAuthorsVal1 = new com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair();
            _returnParentAuthorsVal1.setLabel("Label1013350868");
            java.util.List<java.lang.String> _returnParentAuthorsVal1Value = new java.util.ArrayList<java.lang.String>();
            _returnParentAuthorsVal1.getValue().addAll(_returnParentAuthorsVal1Value);
            _returnParentAuthors.add(_returnParentAuthorsVal1);
            _returnParent.getAuthors().addAll(_returnParentAuthors);
            java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair> _returnParentKeywords = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair _returnParentKeywordsVal1 = new com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair();
            _returnParentKeywordsVal1.setLabel("Label-1683980860");
            java.util.List<java.lang.String> _returnParentKeywordsVal1Value = new java.util.ArrayList<java.lang.String>();
            _returnParentKeywordsVal1.getValue().addAll(_returnParentKeywordsVal1Value);
            _returnParentKeywords.add(_returnParentKeywordsVal1);
            _returnParent.getKeywords().addAll(_returnParentKeywords);
            java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair> _returnParentOther = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair>();
            com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair _returnParentOtherVal1 = new com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair();
            _returnParentOtherVal1.setLabel("Label1299213996");
            java.util.List<java.lang.String> _returnParentOtherVal1Value = new java.util.ArrayList<java.lang.String>();
            _returnParentOtherVal1.getValue().addAll(_returnParentOtherVal1Value);
            _returnParentOther.add(_returnParentOtherVal1);
            _returnParent.getOther().addAll(_returnParentOther);
            _return.setParent(_returnParent);
            java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.LiteRecord> _returnRecords = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.LiteRecord>();
            com.thomsonreuters.wokmws.v3.woksearchlite.LiteRecord _returnRecordsVal1 = new com.thomsonreuters.wokmws.v3.woksearchlite.LiteRecord();
            _returnRecordsVal1.setUid("Uid-333134226");
            java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair> _returnRecordsVal1Title = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getTitle().addAll(_returnRecordsVal1Title);
            java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair> _returnRecordsVal1Source = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getSource().addAll(_returnRecordsVal1Source);
            java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair> _returnRecordsVal1Authors = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getAuthors().addAll(_returnRecordsVal1Authors);
            java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair> _returnRecordsVal1Keywords = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getKeywords().addAll(_returnRecordsVal1Keywords);
            java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair> _returnRecordsVal1Other = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.LabelValuesPair>();
            _returnRecordsVal1.getOther().addAll(_returnRecordsVal1Other);
            _returnRecords.add(_returnRecordsVal1);
            _return.getRecords().addAll(_returnRecords);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new QueryException_Exception("QueryException...");
        //throw new InternalServerException_Exception("InternalServerException...");
        //throw new AuthenticationException_Exception("AuthenticationException...");
        //throw new SessionException_Exception("SessionException...");
        //throw new InvalidInputException_Exception("InvalidInputException...");
        //throw new ESTIWSException_Exception("ESTIWSException...");
    }

}
