
package com.thomsonreuters.wokmws.v3.woksearchlite;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-10-29T11:33:02.900-04:00
 * Generated source version: 2.7.0
 * 
 */
public final class WokSearchLite_WokSearchLitePort_Client {

    private static final QName SERVICE_NAME = new QName("http://woksearchlite.v3.wokmws.thomsonreuters.com", "WokSearchLiteService");

    private WokSearchLite_WokSearchLitePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WokSearchLiteService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WokSearchLiteService ss = new WokSearchLiteService(wsdlURL, SERVICE_NAME);
        WokSearchLite port = ss.getWokSearchLitePort();  
        
        {
        System.out.println("Invoking retrieveById...");
        java.lang.String _retrieveById_databaseId = "_retrieveById_databaseId968513766";
        java.util.List<java.lang.String> _retrieveById_uid = new java.util.ArrayList<java.lang.String>();
        java.lang.String _retrieveById_uidVal1 = "_retrieveById_uidVal-2091314135";
        _retrieveById_uid.add(_retrieveById_uidVal1);
        java.lang.String _retrieveById_queryLanguage = "_retrieveById_queryLanguage1706353061";
        com.thomsonreuters.wokmws.v3.woksearchlite.RetrieveParameters _retrieveById_retrieveParameters = new com.thomsonreuters.wokmws.v3.woksearchlite.RetrieveParameters();
        _retrieveById_retrieveParameters.setFirstRecord(-2006979501);
        _retrieveById_retrieveParameters.setCount(-1693530263);
        java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.SortField> _retrieveById_retrieveParametersSortField = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.SortField>();
        com.thomsonreuters.wokmws.v3.woksearchlite.SortField _retrieveById_retrieveParametersSortFieldVal1 = new com.thomsonreuters.wokmws.v3.woksearchlite.SortField();
        _retrieveById_retrieveParametersSortFieldVal1.setName("Name-118118875");
        _retrieveById_retrieveParametersSortFieldVal1.setSort("Sort1471071138");
        _retrieveById_retrieveParametersSortField.add(_retrieveById_retrieveParametersSortFieldVal1);
        _retrieveById_retrieveParameters.getSortField().addAll(_retrieveById_retrieveParametersSortField);
        try {
            com.thomsonreuters.wokmws.v3.woksearchlite.SearchResults _retrieveById__return = port.retrieveById(_retrieveById_databaseId, _retrieveById_uid, _retrieveById_queryLanguage, _retrieveById_retrieveParameters);
            System.out.println("retrieveById.result=" + _retrieveById__return);

        } catch (QueryException_Exception e) { 
            System.out.println("Expected exception: QueryException has occurred.");
            System.out.println(e.toString());
        } catch (InternalServerException_Exception e) { 
            System.out.println("Expected exception: InternalServerException has occurred.");
            System.out.println(e.toString());
        } catch (AuthenticationException_Exception e) { 
            System.out.println("Expected exception: AuthenticationException has occurred.");
            System.out.println(e.toString());
        } catch (SessionException_Exception e) { 
            System.out.println("Expected exception: SessionException has occurred.");
            System.out.println(e.toString());
        } catch (InvalidInputException_Exception e) { 
            System.out.println("Expected exception: InvalidInputException has occurred.");
            System.out.println(e.toString());
        } catch (ESTIWSException_Exception e) { 
            System.out.println("Expected exception: ESTIWSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking retrieve...");
        java.lang.String _retrieve_queryId = "_retrieve_queryId-586585513";
        com.thomsonreuters.wokmws.v3.woksearchlite.RetrieveParameters _retrieve_retrieveParameters = new com.thomsonreuters.wokmws.v3.woksearchlite.RetrieveParameters();
        _retrieve_retrieveParameters.setFirstRecord(-2069992325);
        _retrieve_retrieveParameters.setCount(972260483);
        java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.SortField> _retrieve_retrieveParametersSortField = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.SortField>();
        com.thomsonreuters.wokmws.v3.woksearchlite.SortField _retrieve_retrieveParametersSortFieldVal1 = new com.thomsonreuters.wokmws.v3.woksearchlite.SortField();
        _retrieve_retrieveParametersSortFieldVal1.setName("Name-714160034");
        _retrieve_retrieveParametersSortFieldVal1.setSort("Sort-474093819");
        _retrieve_retrieveParametersSortField.add(_retrieve_retrieveParametersSortFieldVal1);
        _retrieve_retrieveParameters.getSortField().addAll(_retrieve_retrieveParametersSortField);
        try {
            com.thomsonreuters.wokmws.v3.woksearchlite.SearchResults _retrieve__return = port.retrieve(_retrieve_queryId, _retrieve_retrieveParameters);
            System.out.println("retrieve.result=" + _retrieve__return);

        } catch (QueryException_Exception e) { 
            System.out.println("Expected exception: QueryException has occurred.");
            System.out.println(e.toString());
        } catch (InternalServerException_Exception e) { 
            System.out.println("Expected exception: InternalServerException has occurred.");
            System.out.println(e.toString());
        } catch (AuthenticationException_Exception e) { 
            System.out.println("Expected exception: AuthenticationException has occurred.");
            System.out.println(e.toString());
        } catch (SessionException_Exception e) { 
            System.out.println("Expected exception: SessionException has occurred.");
            System.out.println(e.toString());
        } catch (InvalidInputException_Exception e) { 
            System.out.println("Expected exception: InvalidInputException has occurred.");
            System.out.println(e.toString());
        } catch (ESTIWSException_Exception e) { 
            System.out.println("Expected exception: ESTIWSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking search...");
        com.thomsonreuters.wokmws.v3.woksearchlite.QueryParameters _search_queryParameters = new com.thomsonreuters.wokmws.v3.woksearchlite.QueryParameters();
        _search_queryParameters.setDatabaseId("DatabaseId-2006465452");
        _search_queryParameters.setUserQuery("UserQuery-1916467106");
        java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.EditionDesc> _search_queryParametersEditions = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.EditionDesc>();
        com.thomsonreuters.wokmws.v3.woksearchlite.EditionDesc _search_queryParametersEditionsVal1 = new com.thomsonreuters.wokmws.v3.woksearchlite.EditionDesc();
        _search_queryParametersEditionsVal1.setCollection("Collection-525620133");
        _search_queryParametersEditionsVal1.setEdition("Edition-1904967553");
        _search_queryParametersEditions.add(_search_queryParametersEditionsVal1);
        _search_queryParameters.getEditions().addAll(_search_queryParametersEditions);
        _search_queryParameters.setSymbolicTimeSpan("SymbolicTimeSpan-899502108");
        com.thomsonreuters.wokmws.v3.woksearchlite.TimeSpan _search_queryParametersTimeSpan = new com.thomsonreuters.wokmws.v3.woksearchlite.TimeSpan();
        _search_queryParametersTimeSpan.setBegin("Begin-96176476");
        _search_queryParametersTimeSpan.setEnd("End-460490209");
        _search_queryParameters.setTimeSpan(_search_queryParametersTimeSpan);
        _search_queryParameters.setQueryLanguage("QueryLanguage986858663");
        com.thomsonreuters.wokmws.v3.woksearchlite.RetrieveParameters _search_retrieveParameters = new com.thomsonreuters.wokmws.v3.woksearchlite.RetrieveParameters();
        _search_retrieveParameters.setFirstRecord(235160767);
        _search_retrieveParameters.setCount(-1097284871);
        java.util.List<com.thomsonreuters.wokmws.v3.woksearchlite.SortField> _search_retrieveParametersSortField = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearchlite.SortField>();
        com.thomsonreuters.wokmws.v3.woksearchlite.SortField _search_retrieveParametersSortFieldVal1 = new com.thomsonreuters.wokmws.v3.woksearchlite.SortField();
        _search_retrieveParametersSortFieldVal1.setName("Name-228762292");
        _search_retrieveParametersSortFieldVal1.setSort("Sort1864042653");
        _search_retrieveParametersSortField.add(_search_retrieveParametersSortFieldVal1);
        _search_retrieveParameters.getSortField().addAll(_search_retrieveParametersSortField);
        try {
            com.thomsonreuters.wokmws.v3.woksearchlite.SearchResults _search__return = port.search(_search_queryParameters, _search_retrieveParameters);
            System.out.println("search.result=" + _search__return);

        } catch (QueryException_Exception e) { 
            System.out.println("Expected exception: QueryException has occurred.");
            System.out.println(e.toString());
        } catch (InternalServerException_Exception e) { 
            System.out.println("Expected exception: InternalServerException has occurred.");
            System.out.println(e.toString());
        } catch (AuthenticationException_Exception e) { 
            System.out.println("Expected exception: AuthenticationException has occurred.");
            System.out.println(e.toString());
        } catch (SessionException_Exception e) { 
            System.out.println("Expected exception: SessionException has occurred.");
            System.out.println(e.toString());
        } catch (InvalidInputException_Exception e) { 
            System.out.println("Expected exception: InvalidInputException has occurred.");
            System.out.println(e.toString());
        } catch (ESTIWSException_Exception e) { 
            System.out.println("Expected exception: ESTIWSException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
