
package com.thomsonreuters.wokmws.v3.woksearch;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-10-29T13:06:12.078-04:00
 * Generated source version: 2.7.0
 * 
 */
public final class WokSearch_WokSearchPort_Client {

    private static final QName SERVICE_NAME = new QName("http://woksearch.v3.wokmws.thomsonreuters.com", "WokSearchService");

    private WokSearch_WokSearchPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WokSearchService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WokSearchService ss = new WokSearchService(wsdlURL, SERVICE_NAME);
        WokSearch port = ss.getWokSearchPort();  
        
        {
        System.out.println("Invoking citedReferencesRetrieve...");
        java.lang.String _citedReferencesRetrieve_queryId = "_citedReferencesRetrieve_queryId-1456565825";
        com.thomsonreuters.wokmws.v3.woksearch.RetrieveParameters _citedReferencesRetrieve_retrieveParameters = new com.thomsonreuters.wokmws.v3.woksearch.RetrieveParameters();
        _citedReferencesRetrieve_retrieveParameters.setFirstRecord(-1229350429);
        _citedReferencesRetrieve_retrieveParameters.setCount(-1209239221);
        java.util.List<com.thomsonreuters.wokmws.v3.woksearch.SortField> _citedReferencesRetrieve_retrieveParametersSortField = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearch.SortField>();
        com.thomsonreuters.wokmws.v3.woksearch.SortField _citedReferencesRetrieve_retrieveParametersSortFieldVal1 = new com.thomsonreuters.wokmws.v3.woksearch.SortField();
        _citedReferencesRetrieve_retrieveParametersSortFieldVal1.setName("Name54287285");
        _citedReferencesRetrieve_retrieveParametersSortFieldVal1.setSort("Sort-180548499");
        _citedReferencesRetrieve_retrieveParametersSortField.add(_citedReferencesRetrieve_retrieveParametersSortFieldVal1);
        _citedReferencesRetrieve_retrieveParameters.getSortField().addAll(_citedReferencesRetrieve_retrieveParametersSortField);
        java.util.List<com.thomsonreuters.wokmws.v3.woksearch.ViewField> _citedReferencesRetrieve_retrieveParametersViewField = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearch.ViewField>();
        com.thomsonreuters.wokmws.v3.woksearch.ViewField _citedReferencesRetrieve_retrieveParametersViewFieldVal1 = new com.thomsonreuters.wokmws.v3.woksearch.ViewField();
        _citedReferencesRetrieve_retrieveParametersViewFieldVal1.setCollectionName("CollectionName-652348968");
        java.util.List<java.lang.String> _citedReferencesRetrieve_retrieveParametersViewFieldVal1FieldName = new java.util.ArrayList<java.lang.String>();
        _citedReferencesRetrieve_retrieveParametersViewFieldVal1.getFieldName().addAll(_citedReferencesRetrieve_retrieveParametersViewFieldVal1FieldName);
        _citedReferencesRetrieve_retrieveParametersViewField.add(_citedReferencesRetrieve_retrieveParametersViewFieldVal1);
        _citedReferencesRetrieve_retrieveParameters.getViewField().addAll(_citedReferencesRetrieve_retrieveParametersViewField);
        java.util.List<com.thomsonreuters.wokmws.v3.woksearch.KeyValuePair> _citedReferencesRetrieve_retrieveParametersOption = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearch.KeyValuePair>();
        com.thomsonreuters.wokmws.v3.woksearch.KeyValuePair _citedReferencesRetrieve_retrieveParametersOptionVal1 = new com.thomsonreuters.wokmws.v3.woksearch.KeyValuePair();
        _citedReferencesRetrieve_retrieveParametersOptionVal1.setKey("Key305204724");
        _citedReferencesRetrieve_retrieveParametersOptionVal1.setValue("Value344308919");
        _citedReferencesRetrieve_retrieveParametersOption.add(_citedReferencesRetrieve_retrieveParametersOptionVal1);
        _citedReferencesRetrieve_retrieveParameters.getOption().addAll(_citedReferencesRetrieve_retrieveParametersOption);
        try {
            java.util.List<com.thomsonreuters.wokmws.v3.woksearch.CitedReference> _citedReferencesRetrieve__return = port.citedReferencesRetrieve(_citedReferencesRetrieve_queryId, _citedReferencesRetrieve_retrieveParameters);
            System.out.println("citedReferencesRetrieve.result=" + _citedReferencesRetrieve__return);

        } catch (InternalServerException_Exception e) { 
            System.out.println("Expected exception: InternalServerException has occurred.");
            System.out.println(e.toString());
        } catch (QueryException_Exception e) { 
            System.out.println("Expected exception: QueryException has occurred.");
            System.out.println(e.toString());
        } catch (SessionException_Exception e) { 
            System.out.println("Expected exception: SessionException has occurred.");
            System.out.println(e.toString());
        } catch (AuthenticationException_Exception e) { 
            System.out.println("Expected exception: AuthenticationException has occurred.");
            System.out.println(e.toString());
        } catch (InvalidInputException_Exception e) { 
            System.out.println("Expected exception: InvalidInputException has occurred.");
            System.out.println(e.toString());
        } catch (ESTIWSException_Exception e) { 
            System.out.println("Expected exception: ESTIWSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking relatedRecords...");
        java.lang.String _relatedRecords_databaseId = "_relatedRecords_databaseId-1085376121";
        java.lang.String _relatedRecords_uid = "_relatedRecords_uid1916384312";
        java.util.List<com.thomsonreuters.wokmws.v3.woksearch.EditionDesc> _relatedRecords_editions = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearch.EditionDesc>();
        com.thomsonreuters.wokmws.v3.woksearch.EditionDesc _relatedRecords_editionsVal1 = new com.thomsonreuters.wokmws.v3.woksearch.EditionDesc();
        _relatedRecords_editionsVal1.setCollection("Collection399598720");
        _relatedRecords_editionsVal1.setEdition("Edition1524771428");
        _relatedRecords_editions.add(_relatedRecords_editionsVal1);
        com.thomsonreuters.wokmws.v3.woksearch.TimeSpan _relatedRecords_timeSpan = new com.thomsonreuters.wokmws.v3.woksearch.TimeSpan();
        _relatedRecords_timeSpan.setBegin("Begin-1980948590");
        _relatedRecords_timeSpan.setEnd("End974869209");
        java.lang.String _relatedRecords_queryLanguage = "_relatedRecords_queryLanguage1611603520";
        com.thomsonreuters.wokmws.v3.woksearch.RetrieveParameters _relatedRecords_retrieveParameters = new com.thomsonreuters.wokmws.v3.woksearch.RetrieveParameters();
        _relatedRecords_retrieveParameters.setFirstRecord(-2072235771);
        _relatedRecords_retrieveParameters.setCount(-839462491);
        java.util.List<com.thomsonreuters.wokmws.v3.woksearch.SortField> _relatedRecords_retrieveParametersSortField = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearch.SortField>();
        com.thomsonreuters.wokmws.v3.woksearch.SortField _relatedRecords_retrieveParametersSortFieldVal1 = new com.thomsonreuters.wokmws.v3.woksearch.SortField();
        _relatedRecords_retrieveParametersSortFieldVal1.setName("Name-953634180");
        _relatedRecords_retrieveParametersSortFieldVal1.setSort("Sort-251255249");
        _relatedRecords_retrieveParametersSortField.add(_relatedRecords_retrieveParametersSortFieldVal1);
        _relatedRecords_retrieveParameters.getSortField().addAll(_relatedRecords_retrieveParametersSortField);
        java.util.List<com.thomsonreuters.wokmws.v3.woksearch.ViewField> _relatedRecords_retrieveParametersViewField = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearch.ViewField>();
        com.thomsonreuters.wokmws.v3.woksearch.ViewField _relatedRecords_retrieveParametersViewFieldVal1 = new com.thomsonreuters.wokmws.v3.woksearch.ViewField();
        _relatedRecords_retrieveParametersViewFieldVal1.setCollectionName("CollectionName1561440226");
        java.util.List<java.lang.String> _relatedRecords_retrieveParametersViewFieldVal1FieldName = new java.util.ArrayList<java.lang.String>();
        _relatedRecords_retrieveParametersViewFieldVal1.getFieldName().addAll(_relatedRecords_retrieveParametersViewFieldVal1FieldName);
        _relatedRecords_retrieveParametersViewField.add(_relatedRecords_retrieveParametersViewFieldVal1);
        _relatedRecords_retrieveParameters.getViewField().addAll(_relatedRecords_retrieveParametersViewField);
        java.util.List<com.thomsonreuters.wokmws.v3.woksearch.KeyValuePair> _relatedRecords_retrieveParametersOption = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearch.KeyValuePair>();
        com.thomsonreuters.wokmws.v3.woksearch.KeyValuePair _relatedRecords_retrieveParametersOptionVal1 = new com.thomsonreuters.wokmws.v3.woksearch.KeyValuePair();
        _relatedRecords_retrieveParametersOptionVal1.setKey("Key1468678185");
        _relatedRecords_retrieveParametersOptionVal1.setValue("Value-1033198014");
        _relatedRecords_retrieveParametersOption.add(_relatedRecords_retrieveParametersOptionVal1);
        _relatedRecords_retrieveParameters.getOption().addAll(_relatedRecords_retrieveParametersOption);
        try {
            com.thomsonreuters.wokmws.v3.woksearch.FullRecordSearchResults _relatedRecords__return = port.relatedRecords(_relatedRecords_databaseId, _relatedRecords_uid, _relatedRecords_editions, _relatedRecords_timeSpan, _relatedRecords_queryLanguage, _relatedRecords_retrieveParameters);
            System.out.println("relatedRecords.result=" + _relatedRecords__return);

        } catch (InternalServerException_Exception e) { 
            System.out.println("Expected exception: InternalServerException has occurred.");
            System.out.println(e.toString());
        } catch (QueryException_Exception e) { 
            System.out.println("Expected exception: QueryException has occurred.");
            System.out.println(e.toString());
        } catch (SessionException_Exception e) { 
            System.out.println("Expected exception: SessionException has occurred.");
            System.out.println(e.toString());
        } catch (AuthenticationException_Exception e) { 
            System.out.println("Expected exception: AuthenticationException has occurred.");
            System.out.println(e.toString());
        } catch (InvalidInputException_Exception e) { 
            System.out.println("Expected exception: InvalidInputException has occurred.");
            System.out.println(e.toString());
        } catch (ESTIWSException_Exception e) { 
            System.out.println("Expected exception: ESTIWSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking citingArticles...");
        java.lang.String _citingArticles_databaseId = "_citingArticles_databaseId-1146455723";
        java.lang.String _citingArticles_uid = "_citingArticles_uid255591377";
        java.util.List<com.thomsonreuters.wokmws.v3.woksearch.EditionDesc> _citingArticles_editions = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearch.EditionDesc>();
        com.thomsonreuters.wokmws.v3.woksearch.EditionDesc _citingArticles_editionsVal1 = new com.thomsonreuters.wokmws.v3.woksearch.EditionDesc();
        _citingArticles_editionsVal1.setCollection("Collection-2140007968");
        _citingArticles_editionsVal1.setEdition("Edition-2024788385");
        _citingArticles_editions.add(_citingArticles_editionsVal1);
        com.thomsonreuters.wokmws.v3.woksearch.TimeSpan _citingArticles_timeSpan = new com.thomsonreuters.wokmws.v3.woksearch.TimeSpan();
        _citingArticles_timeSpan.setBegin("Begin-231763601");
        _citingArticles_timeSpan.setEnd("End1601685263");
        java.lang.String _citingArticles_queryLanguage = "_citingArticles_queryLanguage-130414296";
        com.thomsonreuters.wokmws.v3.woksearch.RetrieveParameters _citingArticles_retrieveParameters = new com.thomsonreuters.wokmws.v3.woksearch.RetrieveParameters();
        _citingArticles_retrieveParameters.setFirstRecord(-1495634420);
        _citingArticles_retrieveParameters.setCount(-1247193649);
        java.util.List<com.thomsonreuters.wokmws.v3.woksearch.SortField> _citingArticles_retrieveParametersSortField = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearch.SortField>();
        com.thomsonreuters.wokmws.v3.woksearch.SortField _citingArticles_retrieveParametersSortFieldVal1 = new com.thomsonreuters.wokmws.v3.woksearch.SortField();
        _citingArticles_retrieveParametersSortFieldVal1.setName("Name-62375342");
        _citingArticles_retrieveParametersSortFieldVal1.setSort("Sort-367347329");
        _citingArticles_retrieveParametersSortField.add(_citingArticles_retrieveParametersSortFieldVal1);
        _citingArticles_retrieveParameters.getSortField().addAll(_citingArticles_retrieveParametersSortField);
        java.util.List<com.thomsonreuters.wokmws.v3.woksearch.ViewField> _citingArticles_retrieveParametersViewField = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearch.ViewField>();
        com.thomsonreuters.wokmws.v3.woksearch.ViewField _citingArticles_retrieveParametersViewFieldVal1 = new com.thomsonreuters.wokmws.v3.woksearch.ViewField();
        _citingArticles_retrieveParametersViewFieldVal1.setCollectionName("CollectionName-1614967614");
        java.util.List<java.lang.String> _citingArticles_retrieveParametersViewFieldVal1FieldName = new java.util.ArrayList<java.lang.String>();
        _citingArticles_retrieveParametersViewFieldVal1.getFieldName().addAll(_citingArticles_retrieveParametersViewFieldVal1FieldName);
        _citingArticles_retrieveParametersViewField.add(_citingArticles_retrieveParametersViewFieldVal1);
        _citingArticles_retrieveParameters.getViewField().addAll(_citingArticles_retrieveParametersViewField);
        java.util.List<com.thomsonreuters.wokmws.v3.woksearch.KeyValuePair> _citingArticles_retrieveParametersOption = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearch.KeyValuePair>();
        com.thomsonreuters.wokmws.v3.woksearch.KeyValuePair _citingArticles_retrieveParametersOptionVal1 = new com.thomsonreuters.wokmws.v3.woksearch.KeyValuePair();
        _citingArticles_retrieveParametersOptionVal1.setKey("Key-1169115519");
        _citingArticles_retrieveParametersOptionVal1.setValue("Value1342155550");
        _citingArticles_retrieveParametersOption.add(_citingArticles_retrieveParametersOptionVal1);
        _citingArticles_retrieveParameters.getOption().addAll(_citingArticles_retrieveParametersOption);
        try {
            com.thomsonreuters.wokmws.v3.woksearch.FullRecordSearchResults _citingArticles__return = port.citingArticles(_citingArticles_databaseId, _citingArticles_uid, _citingArticles_editions, _citingArticles_timeSpan, _citingArticles_queryLanguage, _citingArticles_retrieveParameters);
            System.out.println("citingArticles.result=" + _citingArticles__return);

        } catch (InternalServerException_Exception e) { 
            System.out.println("Expected exception: InternalServerException has occurred.");
            System.out.println(e.toString());
        } catch (QueryException_Exception e) { 
            System.out.println("Expected exception: QueryException has occurred.");
            System.out.println(e.toString());
        } catch (SessionException_Exception e) { 
            System.out.println("Expected exception: SessionException has occurred.");
            System.out.println(e.toString());
        } catch (AuthenticationException_Exception e) { 
            System.out.println("Expected exception: AuthenticationException has occurred.");
            System.out.println(e.toString());
        } catch (InvalidInputException_Exception e) { 
            System.out.println("Expected exception: InvalidInputException has occurred.");
            System.out.println(e.toString());
        } catch (ESTIWSException_Exception e) { 
            System.out.println("Expected exception: ESTIWSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking citedReferences...");
        java.lang.String _citedReferences_databaseId = "_citedReferences_databaseId-2001956535";
        java.lang.String _citedReferences_uid = "_citedReferences_uid756151972";
        java.lang.String _citedReferences_queryLanguage = "_citedReferences_queryLanguage198464943";
        com.thomsonreuters.wokmws.v3.woksearch.RetrieveParameters _citedReferences_retrieveParameters = new com.thomsonreuters.wokmws.v3.woksearch.RetrieveParameters();
        _citedReferences_retrieveParameters.setFirstRecord(1870097239);
        _citedReferences_retrieveParameters.setCount(-1894040623);
        java.util.List<com.thomsonreuters.wokmws.v3.woksearch.SortField> _citedReferences_retrieveParametersSortField = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearch.SortField>();
        com.thomsonreuters.wokmws.v3.woksearch.SortField _citedReferences_retrieveParametersSortFieldVal1 = new com.thomsonreuters.wokmws.v3.woksearch.SortField();
        _citedReferences_retrieveParametersSortFieldVal1.setName("Name1190441020");
        _citedReferences_retrieveParametersSortFieldVal1.setSort("Sort-1631591610");
        _citedReferences_retrieveParametersSortField.add(_citedReferences_retrieveParametersSortFieldVal1);
        _citedReferences_retrieveParameters.getSortField().addAll(_citedReferences_retrieveParametersSortField);
        java.util.List<com.thomsonreuters.wokmws.v3.woksearch.ViewField> _citedReferences_retrieveParametersViewField = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearch.ViewField>();
        com.thomsonreuters.wokmws.v3.woksearch.ViewField _citedReferences_retrieveParametersViewFieldVal1 = new com.thomsonreuters.wokmws.v3.woksearch.ViewField();
        _citedReferences_retrieveParametersViewFieldVal1.setCollectionName("CollectionName-1835586025");
        java.util.List<java.lang.String> _citedReferences_retrieveParametersViewFieldVal1FieldName = new java.util.ArrayList<java.lang.String>();
        _citedReferences_retrieveParametersViewFieldVal1.getFieldName().addAll(_citedReferences_retrieveParametersViewFieldVal1FieldName);
        _citedReferences_retrieveParametersViewField.add(_citedReferences_retrieveParametersViewFieldVal1);
        _citedReferences_retrieveParameters.getViewField().addAll(_citedReferences_retrieveParametersViewField);
        java.util.List<com.thomsonreuters.wokmws.v3.woksearch.KeyValuePair> _citedReferences_retrieveParametersOption = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearch.KeyValuePair>();
        com.thomsonreuters.wokmws.v3.woksearch.KeyValuePair _citedReferences_retrieveParametersOptionVal1 = new com.thomsonreuters.wokmws.v3.woksearch.KeyValuePair();
        _citedReferences_retrieveParametersOptionVal1.setKey("Key-1684103283");
        _citedReferences_retrieveParametersOptionVal1.setValue("Value-1154698903");
        _citedReferences_retrieveParametersOption.add(_citedReferences_retrieveParametersOptionVal1);
        _citedReferences_retrieveParameters.getOption().addAll(_citedReferences_retrieveParametersOption);
        try {
            com.thomsonreuters.wokmws.v3.woksearch.CitedReferencesSearchResults _citedReferences__return = port.citedReferences(_citedReferences_databaseId, _citedReferences_uid, _citedReferences_queryLanguage, _citedReferences_retrieveParameters);
            System.out.println("citedReferences.result=" + _citedReferences__return);

        } catch (InternalServerException_Exception e) { 
            System.out.println("Expected exception: InternalServerException has occurred.");
            System.out.println(e.toString());
        } catch (QueryException_Exception e) { 
            System.out.println("Expected exception: QueryException has occurred.");
            System.out.println(e.toString());
        } catch (SessionException_Exception e) { 
            System.out.println("Expected exception: SessionException has occurred.");
            System.out.println(e.toString());
        } catch (AuthenticationException_Exception e) { 
            System.out.println("Expected exception: AuthenticationException has occurred.");
            System.out.println(e.toString());
        } catch (InvalidInputException_Exception e) { 
            System.out.println("Expected exception: InvalidInputException has occurred.");
            System.out.println(e.toString());
        } catch (ESTIWSException_Exception e) { 
            System.out.println("Expected exception: ESTIWSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking retrieve...");
        java.lang.String _retrieve_queryId = "_retrieve_queryId1334513368";
        com.thomsonreuters.wokmws.v3.woksearch.RetrieveParameters _retrieve_retrieveParameters = new com.thomsonreuters.wokmws.v3.woksearch.RetrieveParameters();
        _retrieve_retrieveParameters.setFirstRecord(-785064511);
        _retrieve_retrieveParameters.setCount(1737424037);
        java.util.List<com.thomsonreuters.wokmws.v3.woksearch.SortField> _retrieve_retrieveParametersSortField = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearch.SortField>();
        com.thomsonreuters.wokmws.v3.woksearch.SortField _retrieve_retrieveParametersSortFieldVal1 = new com.thomsonreuters.wokmws.v3.woksearch.SortField();
        _retrieve_retrieveParametersSortFieldVal1.setName("Name-1160348776");
        _retrieve_retrieveParametersSortFieldVal1.setSort("Sort-309644349");
        _retrieve_retrieveParametersSortField.add(_retrieve_retrieveParametersSortFieldVal1);
        _retrieve_retrieveParameters.getSortField().addAll(_retrieve_retrieveParametersSortField);
        java.util.List<com.thomsonreuters.wokmws.v3.woksearch.ViewField> _retrieve_retrieveParametersViewField = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearch.ViewField>();
        com.thomsonreuters.wokmws.v3.woksearch.ViewField _retrieve_retrieveParametersViewFieldVal1 = new com.thomsonreuters.wokmws.v3.woksearch.ViewField();
        _retrieve_retrieveParametersViewFieldVal1.setCollectionName("CollectionName-707575978");
        java.util.List<java.lang.String> _retrieve_retrieveParametersViewFieldVal1FieldName = new java.util.ArrayList<java.lang.String>();
        _retrieve_retrieveParametersViewFieldVal1.getFieldName().addAll(_retrieve_retrieveParametersViewFieldVal1FieldName);
        _retrieve_retrieveParametersViewField.add(_retrieve_retrieveParametersViewFieldVal1);
        _retrieve_retrieveParameters.getViewField().addAll(_retrieve_retrieveParametersViewField);
        java.util.List<com.thomsonreuters.wokmws.v3.woksearch.KeyValuePair> _retrieve_retrieveParametersOption = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearch.KeyValuePair>();
        com.thomsonreuters.wokmws.v3.woksearch.KeyValuePair _retrieve_retrieveParametersOptionVal1 = new com.thomsonreuters.wokmws.v3.woksearch.KeyValuePair();
        _retrieve_retrieveParametersOptionVal1.setKey("Key-1833046090");
        _retrieve_retrieveParametersOptionVal1.setValue("Value-327786702");
        _retrieve_retrieveParametersOption.add(_retrieve_retrieveParametersOptionVal1);
        _retrieve_retrieveParameters.getOption().addAll(_retrieve_retrieveParametersOption);
        try {
            com.thomsonreuters.wokmws.v3.woksearch.FullRecordData _retrieve__return = port.retrieve(_retrieve_queryId, _retrieve_retrieveParameters);
            System.out.println("retrieve.result=" + _retrieve__return);

        } catch (InternalServerException_Exception e) { 
            System.out.println("Expected exception: InternalServerException has occurred.");
            System.out.println(e.toString());
        } catch (QueryException_Exception e) { 
            System.out.println("Expected exception: QueryException has occurred.");
            System.out.println(e.toString());
        } catch (SessionException_Exception e) { 
            System.out.println("Expected exception: SessionException has occurred.");
            System.out.println(e.toString());
        } catch (AuthenticationException_Exception e) { 
            System.out.println("Expected exception: AuthenticationException has occurred.");
            System.out.println(e.toString());
        } catch (InvalidInputException_Exception e) { 
            System.out.println("Expected exception: InvalidInputException has occurred.");
            System.out.println(e.toString());
        } catch (ESTIWSException_Exception e) { 
            System.out.println("Expected exception: ESTIWSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking retrieveById...");
        java.lang.String _retrieveById_databaseId = "_retrieveById_databaseId-166648941";
        java.util.List<java.lang.String> _retrieveById_uid = new java.util.ArrayList<java.lang.String>();
        java.lang.String _retrieveById_uidVal1 = "_retrieveById_uidVal-1722353914";
        _retrieveById_uid.add(_retrieveById_uidVal1);
        java.lang.String _retrieveById_queryLanguage = "_retrieveById_queryLanguage-1038721838";
        com.thomsonreuters.wokmws.v3.woksearch.RetrieveParameters _retrieveById_retrieveParameters = new com.thomsonreuters.wokmws.v3.woksearch.RetrieveParameters();
        _retrieveById_retrieveParameters.setFirstRecord(1122313301);
        _retrieveById_retrieveParameters.setCount(1420735140);
        java.util.List<com.thomsonreuters.wokmws.v3.woksearch.SortField> _retrieveById_retrieveParametersSortField = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearch.SortField>();
        com.thomsonreuters.wokmws.v3.woksearch.SortField _retrieveById_retrieveParametersSortFieldVal1 = new com.thomsonreuters.wokmws.v3.woksearch.SortField();
        _retrieveById_retrieveParametersSortFieldVal1.setName("Name-1674657270");
        _retrieveById_retrieveParametersSortFieldVal1.setSort("Sort1092716235");
        _retrieveById_retrieveParametersSortField.add(_retrieveById_retrieveParametersSortFieldVal1);
        _retrieveById_retrieveParameters.getSortField().addAll(_retrieveById_retrieveParametersSortField);
        java.util.List<com.thomsonreuters.wokmws.v3.woksearch.ViewField> _retrieveById_retrieveParametersViewField = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearch.ViewField>();
        com.thomsonreuters.wokmws.v3.woksearch.ViewField _retrieveById_retrieveParametersViewFieldVal1 = new com.thomsonreuters.wokmws.v3.woksearch.ViewField();
        _retrieveById_retrieveParametersViewFieldVal1.setCollectionName("CollectionName-1064170811");
        java.util.List<java.lang.String> _retrieveById_retrieveParametersViewFieldVal1FieldName = new java.util.ArrayList<java.lang.String>();
        _retrieveById_retrieveParametersViewFieldVal1.getFieldName().addAll(_retrieveById_retrieveParametersViewFieldVal1FieldName);
        _retrieveById_retrieveParametersViewField.add(_retrieveById_retrieveParametersViewFieldVal1);
        _retrieveById_retrieveParameters.getViewField().addAll(_retrieveById_retrieveParametersViewField);
        java.util.List<com.thomsonreuters.wokmws.v3.woksearch.KeyValuePair> _retrieveById_retrieveParametersOption = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearch.KeyValuePair>();
        com.thomsonreuters.wokmws.v3.woksearch.KeyValuePair _retrieveById_retrieveParametersOptionVal1 = new com.thomsonreuters.wokmws.v3.woksearch.KeyValuePair();
        _retrieveById_retrieveParametersOptionVal1.setKey("Key1597369100");
        _retrieveById_retrieveParametersOptionVal1.setValue("Value467990960");
        _retrieveById_retrieveParametersOption.add(_retrieveById_retrieveParametersOptionVal1);
        _retrieveById_retrieveParameters.getOption().addAll(_retrieveById_retrieveParametersOption);
        try {
            com.thomsonreuters.wokmws.v3.woksearch.FullRecordSearchResults _retrieveById__return = port.retrieveById(_retrieveById_databaseId, _retrieveById_uid, _retrieveById_queryLanguage, _retrieveById_retrieveParameters);
            System.out.println("retrieveById.result=" + _retrieveById__return);

        } catch (InternalServerException_Exception e) { 
            System.out.println("Expected exception: InternalServerException has occurred.");
            System.out.println(e.toString());
        } catch (QueryException_Exception e) { 
            System.out.println("Expected exception: QueryException has occurred.");
            System.out.println(e.toString());
        } catch (SessionException_Exception e) { 
            System.out.println("Expected exception: SessionException has occurred.");
            System.out.println(e.toString());
        } catch (AuthenticationException_Exception e) { 
            System.out.println("Expected exception: AuthenticationException has occurred.");
            System.out.println(e.toString());
        } catch (InvalidInputException_Exception e) { 
            System.out.println("Expected exception: InvalidInputException has occurred.");
            System.out.println(e.toString());
        } catch (ESTIWSException_Exception e) { 
            System.out.println("Expected exception: ESTIWSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking search...");
        com.thomsonreuters.wokmws.v3.woksearch.QueryParameters _search_queryParameters = new com.thomsonreuters.wokmws.v3.woksearch.QueryParameters();
        _search_queryParameters.setDatabaseId("DatabaseId-1154492751");
        _search_queryParameters.setUserQuery("UserQuery1456493860");
        java.util.List<com.thomsonreuters.wokmws.v3.woksearch.EditionDesc> _search_queryParametersEditions = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearch.EditionDesc>();
        com.thomsonreuters.wokmws.v3.woksearch.EditionDesc _search_queryParametersEditionsVal1 = new com.thomsonreuters.wokmws.v3.woksearch.EditionDesc();
        _search_queryParametersEditionsVal1.setCollection("Collection12454327");
        _search_queryParametersEditionsVal1.setEdition("Edition1960686519");
        _search_queryParametersEditions.add(_search_queryParametersEditionsVal1);
        _search_queryParameters.getEditions().addAll(_search_queryParametersEditions);
        _search_queryParameters.setSymbolicTimeSpan("SymbolicTimeSpan1338513304");
        com.thomsonreuters.wokmws.v3.woksearch.TimeSpan _search_queryParametersTimeSpan = new com.thomsonreuters.wokmws.v3.woksearch.TimeSpan();
        _search_queryParametersTimeSpan.setBegin("Begin-1718234271");
        _search_queryParametersTimeSpan.setEnd("End-1390892590");
        _search_queryParameters.setTimeSpan(_search_queryParametersTimeSpan);
        _search_queryParameters.setQueryLanguage("QueryLanguage-932834340");
        com.thomsonreuters.wokmws.v3.woksearch.RetrieveParameters _search_retrieveParameters = new com.thomsonreuters.wokmws.v3.woksearch.RetrieveParameters();
        _search_retrieveParameters.setFirstRecord(-1763169635);
        _search_retrieveParameters.setCount(477306990);
        java.util.List<com.thomsonreuters.wokmws.v3.woksearch.SortField> _search_retrieveParametersSortField = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearch.SortField>();
        com.thomsonreuters.wokmws.v3.woksearch.SortField _search_retrieveParametersSortFieldVal1 = new com.thomsonreuters.wokmws.v3.woksearch.SortField();
        _search_retrieveParametersSortFieldVal1.setName("Name-136068499");
        _search_retrieveParametersSortFieldVal1.setSort("Sort-2073124172");
        _search_retrieveParametersSortField.add(_search_retrieveParametersSortFieldVal1);
        _search_retrieveParameters.getSortField().addAll(_search_retrieveParametersSortField);
        java.util.List<com.thomsonreuters.wokmws.v3.woksearch.ViewField> _search_retrieveParametersViewField = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearch.ViewField>();
        com.thomsonreuters.wokmws.v3.woksearch.ViewField _search_retrieveParametersViewFieldVal1 = new com.thomsonreuters.wokmws.v3.woksearch.ViewField();
        _search_retrieveParametersViewFieldVal1.setCollectionName("CollectionName-1194428629");
        java.util.List<java.lang.String> _search_retrieveParametersViewFieldVal1FieldName = new java.util.ArrayList<java.lang.String>();
        _search_retrieveParametersViewFieldVal1.getFieldName().addAll(_search_retrieveParametersViewFieldVal1FieldName);
        _search_retrieveParametersViewField.add(_search_retrieveParametersViewFieldVal1);
        _search_retrieveParameters.getViewField().addAll(_search_retrieveParametersViewField);
        java.util.List<com.thomsonreuters.wokmws.v3.woksearch.KeyValuePair> _search_retrieveParametersOption = new java.util.ArrayList<com.thomsonreuters.wokmws.v3.woksearch.KeyValuePair>();
        com.thomsonreuters.wokmws.v3.woksearch.KeyValuePair _search_retrieveParametersOptionVal1 = new com.thomsonreuters.wokmws.v3.woksearch.KeyValuePair();
        _search_retrieveParametersOptionVal1.setKey("Key82151221");
        _search_retrieveParametersOptionVal1.setValue("Value504060507");
        _search_retrieveParametersOption.add(_search_retrieveParametersOptionVal1);
        _search_retrieveParameters.getOption().addAll(_search_retrieveParametersOption);
        try {
            com.thomsonreuters.wokmws.v3.woksearch.FullRecordSearchResults _search__return = port.search(_search_queryParameters, _search_retrieveParameters);
            System.out.println("search.result=" + _search__return);

        } catch (InternalServerException_Exception e) { 
            System.out.println("Expected exception: InternalServerException has occurred.");
            System.out.println(e.toString());
        } catch (QueryException_Exception e) { 
            System.out.println("Expected exception: QueryException has occurred.");
            System.out.println(e.toString());
        } catch (SessionException_Exception e) { 
            System.out.println("Expected exception: SessionException has occurred.");
            System.out.println(e.toString());
        } catch (AuthenticationException_Exception e) { 
            System.out.println("Expected exception: AuthenticationException has occurred.");
            System.out.println(e.toString());
        } catch (InvalidInputException_Exception e) { 
            System.out.println("Expected exception: InvalidInputException has occurred.");
            System.out.println(e.toString());
        } catch (ESTIWSException_Exception e) { 
            System.out.println("Expected exception: ESTIWSException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
