package com.thomsonreuters.wokmws.cxf.auth;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-10-29T11:32:07.697-04:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://auth.cxf.wokmws.thomsonreuters.com", name = "WOKMWSAuthenticate")
@XmlSeeAlso({ObjectFactory.class})
public interface WOKMWSAuthenticate {

    @RequestWrapper(localName = "closeSession", targetNamespace = "http://auth.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.auth.CloseSession")
    @WebMethod
    @ResponseWrapper(localName = "closeSessionResponse", targetNamespace = "http://auth.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.auth.CloseSessionResponse")
    public void closeSession() throws SessionException_Exception, QueryException_Exception, AuthenticationException_Exception, ESTIWSException_Exception, InternalServerException_Exception, InvalidInputException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "roamingAuthenticate", targetNamespace = "http://auth.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.auth.RoamingAuthenticate")
    @WebMethod
    @ResponseWrapper(localName = "roamingAuthenticateResponse", targetNamespace = "http://auth.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.auth.RoamingAuthenticateResponse")
    public java.lang.String roamingAuthenticate(
        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    ) throws SessionException_Exception, AuthenticationException_Exception, ESTIWSException_Exception, InternalServerException_Exception, InvalidInputException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "authenticate", targetNamespace = "http://auth.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.auth.Authenticate")
    @WebMethod
    @ResponseWrapper(localName = "authenticateResponse", targetNamespace = "http://auth.cxf.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.cxf.auth.AuthenticateResponse")
    public java.lang.String authenticate() throws SessionException_Exception, QueryException_Exception, AuthenticationException_Exception, ESTIWSException_Exception, InternalServerException_Exception, InvalidInputException_Exception;
}
